// ============================================================================
// ui_render.cpp — Blend2D offscreen rendering + cross-platform blit
//
// The offscreen surface management mirrors spectral_view.cpp exactly:
//   Win32 : CreateDIBSection (top-down 32-bit BI_RGB) -> bm.bmBits
//   SWELL : SWELL_CreateMemContext + SWELL_GetCtxFrameBuffer
// Blend2D renders into a BLImage (PRGB32); we copy its scanlines into that
// framebuffer (forcing opaque alpha), then BitBlt into the destination HDC.
// ============================================================================

#include "ui_render.h"
#include "ui_theme.h"

// Blend2D public header. Wrapped to keep the project's strict warning flags
// (-Wconversion/-Wshadow/-Wdouble-promotion) from firing inside library headers.
#if defined(__clang__) || defined(__GNUC__)
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wconversion"
#  pragma GCC diagnostic ignored "-Wshadow"
#  pragma GCC diagnostic ignored "-Wdouble-promotion"
#endif
#include <blend2d/blend2d.h>
#if defined(__clang__) || defined(__GNUC__)
#  pragma GCC diagnostic pop
#endif

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdio>

// Embedded UI fonts (generated by CMake from src/assets/fonts/Inter-*.ttf).
extern const unsigned char g_fontInterMedium[];
extern const unsigned int g_fontInterMedium_size;
extern const unsigned char g_fontInterRegular[];
extern const unsigned int g_fontInterRegular_size;

// --- helpers ---------------------------------------------------------------

static inline BLRgba32 col(uint32_t argb) { return BLRgba32(argb); }
static inline BLRgba32 colA(uint32_t argb, int a) {
  return BLRgba32((uint32_t(a) << 24) | (argb & 0x00FFFFFFu));
}

// Load a BLFontFace from embedded data; returns an empty face on failure (call
// sites guard via create_from_face == BL_SUCCESS, so text degrades gracefully).
static BLFontFace LoadFace(const unsigned char* data, unsigned int size) {
  BLFontData fd;
  if (fd.create_from_data(data, size) != BL_SUCCESS) return BLFontFace();
  BLFontFace f;
  if (f.create_from_data(fd, 0) != BL_SUCCESS) return BLFontFace();
  return f;
}

// Cached faces (created once, live for the process). Medium for values/hero,
// Regular for labels/units/ticks (per design spec weight contrast).
static const BLFontFace& InterMediumFace() {
  static BLFontFace face = LoadFace(g_fontInterMedium, g_fontInterMedium_size);
  return face;
}
static const BLFontFace& InterRegularFace() {
  static BLFontFace face = LoadFace(g_fontInterRegular, g_fontInterRegular_size);
  return face;
}

// Advance width of a string in a font (to lay out adjacent text, e.g. a unit).
static double TextWidth(const BLFont& font, const char* s) {
  BLGlyphBuffer gb;
  gb.set_utf8_text(s);
  BLTextMetrics tm;
  if (font.get_text_metrics(gb, tm) != BL_SUCCESS) return 0.0;
  return tm.advance.x;
}

// Compression gain reduction (dB, <= 0) for an input level, matching
// dynamics_engine.cpp ComputeCompression(): soft-knee, slope = 1/R - 1.
static double CompressionGrDb(double inDb, double thrDb, double ratio, double kneeDb) {
  if (ratio <= 1.0) return 0.0;
  const double slope = 1.0 / ratio - 1.0;   // negative
  const double halfKnee = kneeDb * 0.5;
  const double overshoot = inDb - thrDb;
  if (overshoot <= -halfKnee) return 0.0;
  if (kneeDb > 0.0 && overshoot < halfKnee) {
    const double t = overshoot + halfKnee;
    return slope * t * t / (2.0 * kneeDb);
  }
  return slope * overshoot;
}

// Stacked-stroke additive glow for a path (Blend2D has no blur primitive).
static void GlowStroke(BLContext& ctx, const BLPath& path, uint32_t baseArgb) {
  ctx.set_comp_op(BL_COMP_OP_PLUS);
  struct Pass { double w; int a; };
  const Pass passes[3] = { {7.0, 26}, {4.0, 48}, {2.0, 90} };
  for (const Pass& p : passes) {
    ctx.set_stroke_width(p.w);
    ctx.stroke_path(path, colA(baseArgb, p.a));
  }
  ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
}

// --- cached Blend2D objects (must-do #4: no per-paint image/font allocation) -

struct Gfx {
  BLImage img;
  int imgW = 0, imgH = 0;
  BLFont fTick, fLabel, fUnit, fGrHero, fTab, fValue;
  bool fontsReady = false;

  void ensureFonts() {
    if (fontsReady) return;
    fontsReady =
        fTick  .create_from_face(InterRegularFace(), (float)dynui::kFsTick)   == BL_SUCCESS &&
        fLabel .create_from_face(InterRegularFace(), (float)dynui::kFsLabel)  == BL_SUCCESS &&
        fUnit  .create_from_face(InterRegularFace(), (float)dynui::kFsUnit)   == BL_SUCCESS &&
        fGrHero.create_from_face(InterMediumFace(),  (float)dynui::kFsGrHero) == BL_SUCCESS &&
        fTab   .create_from_face(InterMediumFace(),  (float)dynui::kFsTab)    == BL_SUCCESS &&
        fValue .create_from_face(InterMediumFace(),  (float)dynui::kFsValue)  == BL_SUCCESS;
  }
  // (re)create the offscreen image only when the device pixel size changes.
  bool ensureImage(int devW, int devH) {
    if (imgW != devW || imgH != devH) {
      if (img.create(devW, devH, BL_FORMAT_PRGB32) != BL_SUCCESS) return false;
      imgW = devW; imgH = devH;
    }
    return true;
  }
};

// --- lifecycle -------------------------------------------------------------

UiCanvas::UiCanvas() = default;   // out-of-line: Gfx is complete here (pimpl)

UiCanvas::~UiCanvas()
{
#ifdef _WIN32
  if (m_memBmp) { DeleteObject(m_memBmp); m_memBmp = nullptr; }
  if (m_memDC)  { DeleteDC(m_memDC); m_memDC = nullptr; }
#else
  if (m_memDC)  { SWELL_DeleteGfxContext(m_memDC); m_memDC = nullptr; }
#endif
}

bool UiCanvas::ensure(HDC hdc, int devW, int devH)
{
  if (devW < 1 || devH < 1) return false;
  if (m_memDC && m_w == devW && m_h == devH) return true;

#ifdef _WIN32
  if (m_memBmp) { DeleteObject(m_memBmp); m_memBmp = nullptr; }
  if (m_memDC)  { DeleteDC(m_memDC); m_memDC = nullptr; }
  BITMAPINFO bmi = {};
  bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
  bmi.bmiHeader.biWidth = devW;
  bmi.bmiHeader.biHeight = -devH; // top-down
  bmi.bmiHeader.biPlanes = 1;
  bmi.bmiHeader.biBitCount = 32;
  bmi.bmiHeader.biCompression = BI_RGB;
  void* bits = nullptr;
  m_memBmp = CreateDIBSection(hdc, &bmi, DIB_RGB_COLORS, &bits, nullptr, 0);
  if (!m_memBmp) return false;
  m_memDC = CreateCompatibleDC(hdc);
  if (!m_memDC) { DeleteObject(m_memBmp); m_memBmp = nullptr; return false; }
  SelectObject(m_memDC, m_memBmp);
#else
  if (m_memDC) { SWELL_DeleteGfxContext(m_memDC); m_memDC = nullptr; }
  m_memDC = SWELL_CreateMemContext(hdc, devW, devH);
  if (!m_memDC) return false;
#endif
  m_w = devW;
  m_h = devH;
  return true;
}

// --- composable draw helpers (shared by the spike now; RenderPanel in Phase 2) -

// Transfer-curve plot inside the square well at (px0,py0,plotSide): well bg,
// unity diagonal, reduction wedge, dotted threshold, gate cliff, static curve,
// amber operating-point segment + glow dot, and input-axis dB tick labels.
// Drawn in logical coordinates; mirrors dynamics_engine ComputeCompression math.
static void DrawTransferPlot(BLContext& ctx, const Gfx& gfx,
                             double px0, double py0, double plotSide,
                             const DynCurveParams& p)
{
  const double px1 = px0 + plotSide;
  const double py1 = py0 + plotSide;
  ctx.fill_round_rect(BLRoundRect(px0, py0, plotSide, plotSide, dynui::kRadiusCtrl),
                      col(dynui::kSurface1));

  const double inMin = p.inMinDb, inMax = p.inMaxDb;
  const double span = (inMax - inMin) != 0 ? (inMax - inMin) : 1.0;
  auto dbToX = [&](double db) { return px0 + (db - inMin) / span * plotSide; };
  auto dbToY = [&](double db) { return py1 - (db - inMin) / span * plotSide; };

  // Curve math mirrors dynamics_engine ComputeCompression() steady state. The
  // plotted curve is the COMPRESSION CHARACTERISTIC y = x + GR (per the design
  // spec); makeup gain is a constant offset shown via its own control, NOT baked
  // into the curve (keeps red=reduction and the wedge clean). The GATE onset/depth
  // DO depend on makeup (the engine gates on the post-comp+makeup level), so
  // makeup is used only inside gateGrDb to place the cliff correctly.
  auto compGrDb = [&](double in) {
    return CompressionGrDb(in, p.thresholdDb, p.ratio, p.kneeDb);            // <= 0
  };
  auto gateGrDb = [&](double in, double compGr) -> double {
    if (!p.showGate) return 0.0;
    const double postLvl = in + compGr + p.makeupDb;                         // engine: post-comp+makeup
    if (postLvl >= p.gateThreshDb) return 0.0;
    const double gateRangeNeg = -std::fabs(p.gateRangeDb);                   // engine range is negative
    return std::max(postLvl - p.gateThreshDb, gateRangeNeg);                 // ramp 0 -> range, clamped
  };
  auto compOut = [&](double in) { return in + compGrDb(in); };              // wedge: compression only
  auto outAt   = [&](double in) { const double g = compGrDb(in); return in + g + gateGrDb(in, g); };

  // clip to the plot well so curves never spill over the rounded corners
  ctx.save();
  ctx.clip_to_rect(BLRect(px0, py0, plotSide, plotSide));

  // unity 1:1 diagonal (faint reference)
  ctx.set_stroke_width(1.0);
  ctx.stroke_line(BLLine(px0, py1, px1, py0), col(dynui::kCurveUnity));

  const int N = dynui::kPlotSamples;
  auto sampleDb = [&](int i) { return inMin + span * (double)i / (double)N; };

  // reduction wedge: area between unity diagonal and the COMPRESSION curve (gate
  // excluded so red = compression reduction only), red->transparent
  {
    BLPath wedge;
    wedge.move_to(dbToX(inMin), dbToY(inMin));
    wedge.line_to(dbToX(inMax), dbToY(inMax));        // along the diagonal
    for (int i = N; i >= 0; --i) {                    // back along the curve
      const double in = sampleDb(i);
      wedge.line_to(dbToX(in), dbToY(compOut(in)));
    }
    wedge.close();
    BLGradient g(BLLinearGradientValues(0, py0, 0, py1));
    g.add_stop(0.0, colA(dynui::kGrRed, 70));
    g.add_stop(1.0, colA(dynui::kGrRed, 0));
    ctx.fill_path(wedge, g);
  }

  // dotted threshold line (vertical), persists regardless of overlays
  {
    const double tx = dbToX(p.thresholdDb);
    ctx.set_stroke_width(1.0);
    for (double yy = py0; yy < py1; yy += 5.0)
      ctx.stroke_line(BLLine(tx, yy, tx, std::min(yy + 2.5, py1)),
                      colA(dynui::kInkMuted, 200));
  }

  // static transfer curve (neutral), full shape including the gate drop
  BLPath curve;
  for (int i = 0; i <= N; ++i) {
    const double in = sampleDb(i);
    const double cx = dbToX(in), cy = dbToY(outAt(in));
    if (i == 0) curve.move_to(cx, cy); else curve.line_to(cx, cy);
  }
  ctx.set_stroke_width(2.0);
  ctx.stroke_path(curve, col(dynui::kCurveStatic));

  // gate cliff: re-stroke the input subrange where the gate is active, in violet.
  // Onset is at input (gateThresh - makeup); depth ramps to the gate range and
  // clamps - matches engine min(|gateThr-postLevel|,|gateRange|) on the
  // post-comp+makeup level. Drawn ON the curve (outAt) so it stays continuous.
  if (p.showGate) {
    BLPath gate;
    bool started = false;
    for (int i = 0; i <= N; ++i) {
      const double in = sampleDb(i);
      if (gateGrDb(in, compGrDb(in)) < 0.0) {
        const double cx = dbToX(in), cy = dbToY(outAt(in));
        if (!started) { gate.move_to(cx, cy); started = true; } else gate.line_to(cx, cy);
      }
    }
    if (started) {
      ctx.set_stroke_width(2.0);
      ctx.stroke_path(gate, col(dynui::kGateViolet));
    }
  }

  // live segment up to the operating point (avgPeak), amber + glow
  const bool hasOp = p.avgPeakDb > inMin && p.avgPeakDb <= inMax;
  if (hasOp) {
    BLPath lit;
    bool started = false;
    for (int i = 0; i <= N; ++i) {
      const double in = sampleDb(i);
      if (in > p.avgPeakDb) break;
      const double cx = dbToX(in), cy = dbToY(outAt(in));
      if (!started) { lit.move_to(cx, cy); started = true; } else lit.line_to(cx, cy);
    }
    lit.line_to(dbToX(p.avgPeakDb), dbToY(outAt(p.avgPeakDb)));
    GlowStroke(ctx, lit, dynui::kAmberGlow);
    ctx.set_stroke_width(2.0);
    ctx.stroke_path(lit, col(dynui::kAmber));

    // operating-point dot + glow
    const double dx = dbToX(p.avgPeakDb), dy = dbToY(outAt(p.avgPeakDb));
    ctx.set_comp_op(BL_COMP_OP_PLUS);
    ctx.fill_circle(BLCircle(dx, dy, 7.0), colA(dynui::kAmberGlow, 60));
    ctx.fill_circle(BLCircle(dx, dy, 4.5), colA(dynui::kAmberGlow, 110));
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
    ctx.fill_circle(BLCircle(dx, dy, 3.0), col(dynui::kAmber));
  }

  ctx.restore();   // remove plot clip

  // input-axis dB tick labels on a 12 dB grid within [inMin, inMax]
  if (gfx.fontsReady) {
    const BLFont& f = gfx.fTick;
    const double step = (double)dynui::kTickStepDb;
    for (double db = std::ceil(inMin / step) * step; db <= inMax + 0.001; db += step) {
      char buf[8];
      std::snprintf(buf, sizeof(buf), "%d", (int)std::lround(db));
      ctx.fill_utf8_text(BLPoint(dbToX(db) + 2.0, py1 + 11.0), f, buf,
                         SIZE_MAX, col(dynui::kInkMuted));
    }
  }
}

// GR meter to the right of the plot (anchored at px1): track + downward red fill
// + ticks + peak-hold marker + hero numeric readout. (must-dos #2/#3 refine the
// value + scale at Inc 2; this is the verbatim spike behaviour.)
static void DrawGrMeter(BLContext& ctx, const Gfx& gfx,
                        double px1, double py0, double plotSide,
                        const DynCurveParams& p, bool withNumber = true)
{
  // Value = real engine average GR (p.avgGrDb, negative) -> magnitude: the truthful
  // applied/average GR (what auto-makeup compensated, what Apply does). Scale = the
  // PLOT's px-per-dB so the fill height equals the curve-to-diagonal gap (must-do
  // #2: shared scale, not a private 24 dB range).
  const double span = (p.inMaxDb - p.inMinDb) != 0 ? (p.inMaxDb - p.inMinDb) : 1.0;
  const double pxPerDb = plotSide / span;
  const double grMag = std::max(0.0, -p.avgGrDb);
  const double meterX = px1 + (double)dynui::kMeterGap;
  const double barW = (double)dynui::kMeterBarW;
  const double barTop = py0;
  const double barH = plotSide;

  ctx.fill_round_rect(BLRoundRect(meterX, barTop, barW, barH, 4.0),
                      col(dynui::kSurface2));
  const double fillH = std::clamp(grMag * pxPerDb, 0.0, barH);
  if (fillH > 0.5) {
    BLGradient g(BLLinearGradientValues(0, barTop, 0, barTop + barH));
    g.add_stop(0.0, col(dynui::kGrRed));
    g.add_stop(1.0, colA(dynui::kGrRed, 120));
    ctx.fill_round_rect(BLRoundRect(meterX, barTop, barW, fillH, 4.0), g);
    ctx.fill_rect(BLRect(meterX, barTop + fillH - 1.0, barW, 2.0),
                  col(dynui::kAmberGlow));   // peak-hold marker
  }
  const double ticks[] = { 0.0, 3.0, 6.0, 12.0, 24.0 };
  ctx.set_stroke_width(1.0);
  for (double t : ticks) {
    const double ty = barTop + std::clamp(t * pxPerDb, 0.0, barH);
    ctx.stroke_line(BLLine(meterX - 3.0, ty, meterX, ty), colA(dynui::kInkMuted, 200));
  }

  // Numeric hero column (spike layout). The premium panel passes withNumber=false
  // and renders the GR hero number in the header instead (compact grid needs the
  // body width for the knob grid).
  if (withNumber && gfx.fontsReady) {
    const double numX = meterX + barW + (double)dynui::kMeterNumGap;
    char num[16];
    std::snprintf(num, sizeof(num), "%.1f", grMag);
    ctx.fill_utf8_text(BLPoint(numX, barTop + 13.0), gfx.fLabel, "GR", SIZE_MAX,
                       col(dynui::kInkSecondary));
    ctx.fill_utf8_text(BLPoint(numX, barTop + 40.0), gfx.fGrHero, num, SIZE_MAX,
                       col(dynui::kGrRed));
    const double numAdvance = TextWidth(gfx.fGrHero, num);
    ctx.fill_utf8_text(BLPoint(numX + numAdvance + 5.0, barTop + 40.0), gfx.fUnit, "dB",
                       SIZE_MAX, col(dynui::kInkMuted));
  }
}

// --- knob grid (Inc 4) -----------------------------------------------------

// Param index -> (tab, column, row) in the compact knob grid. Tab 0=Compressor
// (DYNAMICS column 0: Thresh/Ratio/Knee/Makeup; TIME column 1: Attack/Release/
// L.ahead), tab 1=Gate (G.Thr/G.Range/G.Hold), tab 2=View (no knobs). Matches the
// SLIDER_DEFS order in dynamics_panel.cpp. The single IA source for render + hit.
struct KnobSlot { int tab, col, row; };
static const KnobSlot KNOB_SLOTS[10] = {
  { 0, 0, 0 },  // 0  Thresh   (Compressor / DYNAMICS)
  { 0, 0, 1 },  // 1  Ratio
  { 0, 0, 2 },  // 2  Knee
  { 0, 1, 0 },  // 3  Attack   (Compressor / TIME)
  { 0, 1, 1 },  // 4  Release
  { 0, 0, 3 },  // 5  Makeup   (Compressor / DYNAMICS)
  { 0, 1, 2 },  // 6  L.ahead  (Compressor / TIME)
  { 1, 0, 0 },  // 7  G.Thr    (Gate)
  { 1, 0, 1 },  // 8  G.Range
  { 1, 0, 2 },  // 9  G.Hold
};

static inline double Deg2Rad(double d) { return d * 3.14159265358979323846 / 180.0; }

// One knob in its cell: arc track (270deg) + value fill arc + center cap +
// indicator line + default-value tick on the ring, with the UPPERCASE label and
// value/unit text in a column to the right. Gate knobs fill violet, others amber.
static void DrawKnob(BLContext& ctx, const Gfx& gfx, const URect& cell, const KnobVM& k)
{
  if (cell.w < 1.0) return;   // not on the active tab
  const double dia = (double)dynui::kKnobDiaSm;
  const double r   = dia * 0.5;
  const double cx  = cell.x + 2.0 + r;
  const double cy  = cell.y + cell.h * 0.5;
  const double a0  = Deg2Rad(dynui::kKnobArcStartDeg);
  const double sw  = Deg2Rad(dynui::kKnobArcSweepDeg);
  const double norm = std::clamp(k.norm, 0.0, 1.0);
  const uint32_t fillCol = k.isGate ? dynui::kGateViolet : dynui::kAmber;

  // ring track (full sweep)
  ctx.set_stroke_width(3.0);
  { BLPath p; p.arc_to(cx, cy, r, r, a0, sw, true); ctx.stroke_path(p, col(dynui::kSurface2)); }
  // value fill (start -> norm)
  if (norm > 0.001) {
    BLPath p; p.arc_to(cx, cy, r, r, a0, sw * norm, true);
    ctx.stroke_path(p, col(fillCol));
  }
  // center cap (faint depth)
  ctx.fill_circle(BLCircle(cx, cy, r - 4.5), col(dynui::kSurface3));
  // indicator line at the current angle
  {
    const double a = a0 + sw * norm;
    ctx.set_stroke_width(2.0);
    ctx.stroke_line(BLLine(cx + std::cos(a) * (r - 12.0), cy + std::sin(a) * (r - 12.0),
                           cx + std::cos(a) * (r - 3.0),  cy + std::sin(a) * (r - 3.0)),
                    col(fillCol));
  }
  // default-value tick notch just outside the ring
  {
    const double a = a0 + sw * std::clamp(k.defaultNorm, 0.0, 1.0);
    const double r0 = r + 1.0, r1 = r + 1.0 + (double)dynui::kDefaultTickLen;
    ctx.set_stroke_width(1.0);
    ctx.stroke_line(BLLine(cx + std::cos(a) * r0, cy + std::sin(a) * r0,
                           cx + std::cos(a) * r1, cy + std::sin(a) * r1),
                    colA(dynui::kInkMuted, 200));
  }
  // label + value text column to the right of the knob
  if (gfx.fontsReady) {
    const double tx = cell.x + dia + (double)dynui::kKnobTextGap;
    char up[24];
    int n = 0;
    for (const char* s = k.label ? k.label : ""; *s && n < (int)sizeof(up) - 1; ++s)
      up[n++] = (char)std::toupper((unsigned char)*s);
    up[n] = '\0';
    ctx.fill_utf8_text(BLPoint(tx, cy - 3.0), gfx.fLabel, up, SIZE_MAX, col(dynui::kInkSecondary));

    // Value number (16px primary) + unit (11px muted) on its own advance, per the
    // type spec - keeps long readouts ("1000 ms") inside the content margin and lets
    // ":1" abut the number. Auto-makeup shows the computed value with a muted "auto".
    char num[24];
    std::snprintf(num, sizeof(num), k.precision == 1 ? "%.1f" : "%.0f", k.value);
    const double vy = cy + 15.0;
    ctx.fill_utf8_text(BLPoint(tx, vy), gfx.fValue, num, SIZE_MAX, col(dynui::kInkPrimary));
    const char* unit = k.showAuto ? "auto" : (k.unit ? k.unit : "");
    if (*unit) {
      const bool abut = (unit[0] == ':');   // ratio ":1" sits flush against the number
      const double ux = tx + TextWidth(gfx.fValue, num) + (abut ? 1.0 : 4.0);
      ctx.fill_utf8_text(BLPoint(ux, vy), gfx.fUnit, unit, SIZE_MAX, col(dynui::kInkMuted));
    }
  }
}

// Ensure the platform surface + cached BLImage/fonts are ready at devW x devH.
bool UiCanvas::prepareSurface(HDC hdc, int devW, int devH)
{
  if (!ensure(hdc, devW, devH)) return false;
  if (!m_gfx) m_gfx = std::make_unique<Gfx>();
  m_gfx->ensureFonts();
  return m_gfx->ensureImage(devW, devH);
}

// Copy the rendered BLImage scanlines into the platform framebuffer (forcing
// opaque alpha), then scaled-blit to the destination DC. dpr==1 -> devW==w -> 1:1
// (Windows/Linux unchanged); dpr>1 onto the real Retina window DC -> SWELL maps
// the 2x source onto the 2x backing => crisp HiDPI. (Plain BitBlt(devW,devH) would
// place device-sized px at a logical position = 2x-too-large; the BitBlt-1:1 trap
// documented in .harness/design_phase2_architecture.md.)
void UiCanvas::presentSurface(HDC hdc, int x, int y, int w, int h, int devW, int devH)
{
  unsigned int* fbuf = nullptr;
#ifdef _WIN32
  BITMAP bm;
  if (GetObject(m_memBmp, sizeof(bm), &bm)) fbuf = (unsigned int*)bm.bmBits;
#else
  fbuf = (unsigned int*)SWELL_GetCtxFrameBuffer(m_memDC);
#endif
  if (!fbuf) return;

  BLImageData dat;
  if (m_gfx->img.get_data(&dat) != BL_SUCCESS) return;
  if (!dat.pixel_data) return;
  if (dat.stride <= 0 || (dat.stride % 4) != 0 || dat.stride < (intptr_t)devW * 4) return;
  const uint8_t* srcBase = (const uint8_t*)dat.pixel_data;
  for (int row = 0; row < devH; ++row) {
    const unsigned int* s = (const unsigned int*)(srcBase + (intptr_t)row * dat.stride);
    unsigned int* d = fbuf + (size_t)row * (size_t)devW;
    for (int col2 = 0; col2 < devW; ++col2)
      d[col2] = s[col2] | 0xFF000000u;
  }
  StretchBlt(hdc, x, y, w, h, m_memDC, 0, 0, devW, devH, SRCCOPY);
}

// --- the hero render (spike) -----------------------------------------------

void UiCanvas::RenderTransferCurve(HDC hdc, int x, int y, int w, int h, double dpr,
                                   const DynCurveParams& p)
{
  if (!hdc || w < 8 || h < 8) return;
  if (dpr < 1.0) dpr = 1.0;
  const int devW = (int)std::lround(w * dpr);
  const int devH = (int)std::lround(h * dpr);
  if (!prepareSurface(hdc, devW, devH)) return;
  {
    BLContext ctx;
    if (ctx.begin(m_gfx->img) != BL_SUCCESS) return;
    ctx.clear_all();                // cached image persists prior pixels - start clean
    ctx.scale(dpr);                 // draw everything in LOGICAL coordinates
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);

    const double W = w, H = h;

    // --- panel slab: vertical gradient + rounded body + top hairline highlight
    {
      BLGradient bg(BLLinearGradientValues(0, 0, 0, H));
      bg.add_stop(0.0, col(dynui::kSurface1));
      bg.add_stop(1.0, col(dynui::kSurface0));
      ctx.fill_round_rect(BLRoundRect(0, 0, W, H, dynui::kRadiusPanel), bg);
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(0.5, 0.5, W - 1, H - 1, dynui::kRadiusPanel),
                            col(dynui::kHairline));
    }

    // --- plot well geometry (square, inset); helpers draw the content ---
    const double pad = dynui::kPanelPad;
    const double plotSide = std::min(W - 2 * pad, H - 2 * pad);
    const double px0 = pad;
    const double py0 = (H - plotSide) * 0.5;
    const double px1 = px0 + plotSide;

    DrawTransferPlot(ctx, *m_gfx, px0, py0, plotSide, p);
    DrawGrMeter(ctx, *m_gfx, px1, py0, plotSide, p);

    if (ctx.end() != BL_SUCCESS) return;
  }
  presentSurface(hdc, x, y, w, h, devW, devH);
}

// --- panel layout + chrome (Inc 3b) ----------------------------------------

DynLayout ComputeDynLayout(double w, double h, int activeTab)
{
  DynLayout L;
  const double pad = dynui::kPanelPad;
  L.header = { 0, 0, w, (double)dynui::kHeaderH };
  L.footer = { 0, h - (double)dynui::kFooterH, w, (double)dynui::kFooterH };

  const double hMid = L.header.h * 0.5;
  L.closeBtn = { w - pad - 18.0, hMid - 9.0, 18.0, 18.0 };
  L.abBtn    = { L.closeBtn.x - 48.0, hMid - 11.0, 40.0, 22.0 };
  L.preset   = { pad + 96.0, hMid - 11.0, 120.0, 22.0 };

  const double bodyTop = L.header.h;
  const double bodyH = L.footer.y - bodyTop;

  // Hero transfer plot: square on the LEFT, sized to the body height. The GR meter
  // is a bar-only column right of it (the hero number lives in the header for this
  // compact grid). The remaining width on the right holds the 2-col knob grid.
  const double plotSide = std::max(40.0, std::min(bodyH - 2.0 * pad, (w - 2.0 * pad) * 0.40));
  const double bodyMid = bodyTop + bodyH * 0.5;
  L.plotWell = { pad, bodyMid - plotSide * 0.5, plotSide, plotSide };
  L.grMeter  = { L.plotWell.x + plotSide + (double)dynui::kMeterGap, L.plotWell.y,
                 (double)dynui::kMeterBarW, plotSide };

  // Knob grid: kKnobCols x kKnobRows cells filling the band right of the meter,
  // vertically aligned with the plot. Each param maps to a (tab,col,row) slot;
  // off-tab params get an empty rect so render + hit-test both skip them.
  const double gridX = L.grMeter.x + L.grMeter.w + (double)dynui::kKnobGridGap;
  const double gridR = w - pad;
  const double colGap = (double)dynui::kKnobColGap;
  const double cellW = (gridR - gridX - colGap * (dynui::kKnobCols - 1)) / (double)dynui::kKnobCols;
  const double cellH = plotSide / (double)dynui::kKnobRows;
  for (int i = 0; i < 10; ++i) {
    const KnobSlot& s = KNOB_SLOTS[i];
    L.knob[i] = (s.tab == activeTab)
      ? URect{ gridX + (double)s.col * (cellW + colGap), L.plotWell.y + (double)s.row * cellH,
               cellW, cellH }
      : URect{ 0, 0, 0, 0 };
  }

  const double fMid = L.footer.y + L.footer.h * 0.5;
  L.apply = { pad, fMid - 12.0, 84.0, 24.0 };
  const double segW = 86.0, segGap = 2.0;
  const double pillW = 3.0 * segW + 2.0 * segGap;
  const double pillX = w - pad - pillW;
  for (int i = 0; i < 3; ++i)
    L.tabSeg[i] = { pillX + (double)i * (segW + segGap), fMid - 12.0, segW, 24.0 };
  return L;
}

static void FillURound(BLContext& ctx, const URect& r, double rad, uint32_t argb) {
  ctx.fill_round_rect(BLRoundRect(r.x, r.y, r.w, r.h, rad), col(argb));
}

// Horizontally-centered text within rect r (approx vertical centering).
static void TextCentered(BLContext& ctx, const BLFont& f, const URect& r,
                         const char* s, uint32_t argb) {
  const double tw = TextWidth(f, s);
  ctx.fill_utf8_text(BLPoint(r.x + (r.w - tw) * 0.5, r.y + r.h * 0.5 + 4.0), f, s,
                     SIZE_MAX, col(argb));
}

static void DrawHeader(BLContext& ctx, const Gfx& gfx, const DynLayout& L, const DynPanelVM& vm) {
  if (gfx.fontsReady) {
    ctx.fill_utf8_text(BLPoint(dynui::kPanelPad, L.header.h * 0.5 + 5.0), gfx.fValue,
                       "DYNAMICS", SIZE_MAX, col(dynui::kInkPrimary));
    FillURound(ctx, L.preset, dynui::kRadiusCtrl, dynui::kSurface2);
    ctx.fill_utf8_text(BLPoint(L.preset.x + 8.0, L.preset.y + L.preset.h * 0.5 + 4.0),
                       gfx.fLabel, vm.presetName ? vm.presetName : "Preset", SIZE_MAX,
                       col(dynui::kInkSecondary));

    // GR hero readout: "GR <n> dB", right-aligned just left of the A/B button. This
    // is the load-bearing number from the engine average GR (truthful applied GR).
    char num[16];
    std::snprintf(num, sizeof(num), "%.1f", std::max(0.0, -vm.curve.avgGrDb));
    const double unitW = TextWidth(gfx.fUnit, "dB");
    const double numW  = TextWidth(gfx.fGrHero, num);
    const double lblW  = TextWidth(gfx.fLabel, "GR");
    const double xR    = L.abBtn.x - 12.0;
    const double unitX = xR - unitW;
    const double numX  = unitX - 4.0 - numW;
    const double lblX  = numX - 6.0 - lblW;
    const double baseY = L.header.h * 0.5 + 7.0;
    ctx.fill_utf8_text(BLPoint(lblX,  baseY), gfx.fLabel,  "GR", SIZE_MAX, col(dynui::kInkSecondary));
    ctx.fill_utf8_text(BLPoint(numX,  baseY), gfx.fGrHero, num,  SIZE_MAX, col(dynui::kGrRed));
    ctx.fill_utf8_text(BLPoint(unitX, baseY), gfx.fUnit,   "dB", SIZE_MAX, col(dynui::kInkMuted));

    FillURound(ctx, L.abBtn, dynui::kRadiusCtrl, dynui::kSurface2);
    TextCentered(ctx, gfx.fLabel, L.abBtn, "A/B", dynui::kInkSecondary);
    TextCentered(ctx, gfx.fValue, L.closeBtn, "x", dynui::kInkMuted);
  }
  ctx.set_stroke_width(1.0);
  ctx.stroke_line(BLLine(0, L.header.h, L.header.w, L.header.h), col(dynui::kHairline));
}

static void DrawTabBar(BLContext& ctx, const Gfx& gfx, const DynLayout& L, int activeTab) {
  const char* labels[3] = { "COMP", "GATE", "VIEW" };
  for (int i = 0; i < 3; ++i) {
    const URect& s = L.tabSeg[i];
    const bool active = (i == activeTab);
    FillURound(ctx, s, dynui::kRadiusCtrl, active ? dynui::kSurface3 : dynui::kSurface1);
    if (active)
      ctx.fill_rect(BLRect(s.x + 6.0, s.y + s.h - 2.0, s.w - 12.0, 2.0), col(dynui::kAmber));
    if (gfx.fontsReady)
      TextCentered(ctx, gfx.fTab, s, labels[i], active ? dynui::kAmber : dynui::kInkSecondary);
  }
}

static void DrawFooter(BLContext& ctx, const Gfx& gfx, const DynLayout& L) {
  ctx.set_stroke_width(1.0);
  ctx.stroke_line(BLLine(0, L.footer.y, L.footer.w, L.footer.y), col(dynui::kHairline));
  FillURound(ctx, L.apply, dynui::kRadiusCtrl, dynui::kAmber);
  if (gfx.fontsReady)
    TextCentered(ctx, gfx.fValue, L.apply, "Apply", dynui::kSurface0);
}

// --- the premium panel -----------------------------------------------------

void UiCanvas::RenderPanel(HDC hdc, int x, int y, int w, int h, double dpr,
                           const DynPanelVM& vm)
{
  if (!hdc || w < 8 || h < 8) return;
  if (dpr < 1.0) dpr = 1.0;
  const int devW = (int)std::lround(w * dpr);
  const int devH = (int)std::lround(h * dpr);
  if (!prepareSurface(hdc, devW, devH)) return;
  {
    BLContext ctx;
    if (ctx.begin(m_gfx->img) != BL_SUCCESS) return;
    ctx.clear_all();
    ctx.scale(dpr);
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);

    const double W = w, H = h;

    // panel slab: vertical gradient + rounded body + top hairline highlight
    {
      BLGradient bg(BLLinearGradientValues(0, 0, 0, H));
      bg.add_stop(0.0, col(dynui::kSurface1));
      bg.add_stop(1.0, col(dynui::kSurface0));
      ctx.fill_round_rect(BLRoundRect(0, 0, W, H, dynui::kRadiusPanel), bg);
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(0.5, 0.5, W - 1, H - 1, dynui::kRadiusPanel),
                            col(dynui::kHairline));
    }

    // Full chrome from the shared layout (header / tab pill / footer) + transfer
    // plot + bar-only GR meter (number is in the header) + the per-tab knob grid.
    // Hit-testing shares the same ComputeDynLayout(activeTab) so clicks always
    // match what is drawn.
    const DynLayout L = ComputeDynLayout(W, H, vm.activeTab);
    DrawHeader(ctx, *m_gfx, L, vm);
    DrawTabBar(ctx, *m_gfx, L, vm.activeTab);
    DrawFooter(ctx, *m_gfx, L);
    DrawTransferPlot(ctx, *m_gfx, L.plotWell.x, L.plotWell.y, L.plotWell.w, vm.curve);
    DrawGrMeter(ctx, *m_gfx, L.plotWell.x + L.plotWell.w, L.plotWell.y, L.plotWell.w,
                vm.curve, /*withNumber=*/false);
    for (int i = 0; i < 10; ++i)
      DrawKnob(ctx, *m_gfx, L.knob[i], vm.knobs[i]);

    if (ctx.end() != BL_SUCCESS) return;
  }
  presentSurface(hdc, x, y, w, h, devW, devH);
}
