// ============================================================================
// ui_render.cpp — Blend2D offscreen rendering + cross-platform blit
//
// The offscreen surface management mirrors spectral_view.cpp exactly:
//   Win32 : CreateDIBSection (top-down 32-bit BI_RGB) -> bm.bmBits
//   SWELL : SWELL_CreateMemContext + SWELL_GetCtxFrameBuffer
// Blend2D renders into a BLImage (PRGB32); we copy its scanlines into that
// framebuffer (forcing opaque alpha), then BitBlt into the destination HDC.
// ============================================================================

#include "ui_render.h"
#include "ui_theme.h"

// Blend2D public header. Wrapped to keep the project's strict warning flags
// (-Wconversion/-Wshadow/-Wdouble-promotion) from firing inside library headers.
#if defined(__clang__) || defined(__GNUC__)
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wconversion"
#  pragma GCC diagnostic ignored "-Wshadow"
#  pragma GCC diagnostic ignored "-Wdouble-promotion"
#endif
#include <blend2d/blend2d.h>
#if defined(__clang__) || defined(__GNUC__)
#  pragma GCC diagnostic pop
#endif

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdio>

// Embedded UI fonts (generated by CMake from src/assets/fonts/Inter-*.ttf).
extern const unsigned char g_fontInterMedium[];
extern const unsigned int g_fontInterMedium_size;
extern const unsigned char g_fontInterRegular[];
extern const unsigned int g_fontInterRegular_size;

// --- helpers ---------------------------------------------------------------

static inline BLRgba32 col(uint32_t argb) { return BLRgba32(argb); }
static inline BLRgba32 colA(uint32_t argb, int a) {
  return BLRgba32((uint32_t(a) << 24) | (argb & 0x00FFFFFFu));
}

// Load a BLFontFace from embedded data; returns an empty face on failure (call
// sites guard via create_from_face == BL_SUCCESS, so text degrades gracefully).
static BLFontFace LoadFace(const unsigned char* data, unsigned int size) {
  BLFontData fd;
  if (fd.create_from_data(data, size) != BL_SUCCESS) return BLFontFace();
  BLFontFace f;
  if (f.create_from_data(fd, 0) != BL_SUCCESS) return BLFontFace();
  return f;
}

// Cached faces (created once, live for the process). Medium for values/hero,
// Regular for labels/units/ticks (per design spec weight contrast).
static const BLFontFace& InterMediumFace() {
  static BLFontFace face = LoadFace(g_fontInterMedium, g_fontInterMedium_size);
  return face;
}
static const BLFontFace& InterRegularFace() {
  static BLFontFace face = LoadFace(g_fontInterRegular, g_fontInterRegular_size);
  return face;
}

// Advance width of a string in a font (to lay out adjacent text, e.g. a unit).
static double TextWidth(const BLFont& font, const char* s) {
  BLGlyphBuffer gb;
  gb.set_utf8_text(s);
  BLTextMetrics tm;
  if (font.get_text_metrics(gb, tm) != BL_SUCCESS) return 0.0;
  return tm.advance.x;
}

// Static-curve slope factor, MIRRORS DynSlopeFromRatio in dynamics_engine.h
// (kept local: this renderer carries no engine types beyond DynCurveParams).
// r >= 1 classic, r == 0 -> Inf:1 (S = -1), r < 0 -> over-compression (S < -1).
static double SlopeFromRatioUi(double r) {
  if (r == 0.0) return -1.0;
  if (r < 0.0) return 1.0 / r - 1.0;
  return 1.0 / (r < 1.0 ? 1.0 : r) - 1.0;
}

// Compression gain change (dB) for an input level, matching dynamics_engine.cpp
// ComputeCompression(): soft-knee gain computer, downward (reduce above thresh)
// or upward (boost below thresh, mirrored knee, min(GR, maxBoost) cap, boost
// floored at the gate threshold on the RAW input level - the gate always wins).
static double CompressionGrDb(double inDb, const DynCurveParams& p) {
  const double slope = SlopeFromRatioUi(p.ratio);
  const double halfKnee = p.kneeDb * 0.5;
  const double overshoot = inDb - p.thresholdDb;
  const bool hasDown = (p.mode != 1), hasUp = (p.mode != 0);
  // BOTH: knee centers shift +-halfKnee (dead-band leveler; same-center knees
  // cancel exactly) - mirrors dynamics_engine.cpp ComputeCompression.
  const double oDn = (p.mode == 2) ? overshoot - halfKnee : overshoot;
  const double oUp = (p.mode == 2) ? overshoot + halfKnee : overshoot;
  double g = 0.0;
  if (p.compBypass) return 0.0;   // stage bypassed: no comp contribution at all
  if (hasDown) {
    if (p.kneeDb > 0.0 && oDn > -halfKnee && oDn < halfKnee) {
      const double t = oDn + halfKnee;
      g += slope * t * t / (2.0 * p.kneeDb);
    } else if (oDn > 0.0) {
      g += slope * oDn;
    }
  }
  if (hasUp) {
    double gUp = 0.0;
    if (p.kneeDb > 0.0 && oUp > -halfKnee && oUp < halfKnee) {
      const double t = oUp - halfKnee;                     // mirrored knee quadratic
      gUp = -slope * t * t / (2.0 * p.kneeDb);
    } else if (oUp < 0.0) {
      gUp = slope * oUp;                                   // boost below threshold
    }
    gUp = std::min(gUp, p.maxBoostDb);
    if (p.showGate && inDb < p.gateThreshDb) gUp = 0.0;    // gate-coupled boost floor
    g += gUp;
  }
  return g;
}

// Full output transfer at an input level: y = x + compGR + makeup + gateGR (mirrors
// dynamics_engine ComputeCompression :306). Shared by the plotted curve and the
// curve-handle positions so the handle always sits exactly on the drawn line.
static double CurveOutDb(double in, const DynCurveParams& p) {
  const double g = CompressionGrDb(in, p);
  double out = in + g + p.makeupDb;
  if (p.showGate) {
    // Gate detection domain mirrors the engine: Down = post-comp pre-makeup,
    // Up = RAW input (boosted noise must never hold the gate open).
    const double detect = (p.mode != 0) ? in : in + g;
    // Closed-state ("basic") expander curve: slope Rg-1 below the open
    // threshold, clamped to range. Hysteresis only affects the time behavior
    // (band shading), never this static curve.
    if (detect < p.gateThreshDb) {
      const double gateSlope = std::max(1.0, p.gateRatio) - 1.0;
      out += std::max(gateSlope * (detect - p.gateThreshDb), -std::fabs(p.gateRangeDb));
    }
  }
  return out;
}

// Stacked-stroke additive glow for a path (Blend2D has no blur primitive).
static void GlowStroke(BLContext& ctx, const BLPath& path, uint32_t baseArgb) {
  ctx.set_comp_op(BL_COMP_OP_PLUS);
  struct Pass { double w; int a; };
  const Pass passes[3] = { {7.0, 26}, {4.0, 48}, {2.0, 90} };
  for (const Pass& p : passes) {
    ctx.set_stroke_width(p.w);
    ctx.stroke_path(path, colA(baseArgb, p.a));
  }
  ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
}

// --- cached Blend2D objects (must-do #4: no per-paint image/font allocation) -

struct Gfx {
  BLImage img;
  int imgW = 0, imgH = 0;
  BLFont fTick, fLabel, fUnit, fGrHero, fTab, fValue;
  bool fontsReady = false;

  void ensureFonts() {
    if (fontsReady) return;
    fontsReady =
        fTick  .create_from_face(InterRegularFace(), (float)dynui::kFsTick)   == BL_SUCCESS &&
        fLabel .create_from_face(InterRegularFace(), (float)dynui::kFsLabel)  == BL_SUCCESS &&
        fUnit  .create_from_face(InterRegularFace(), (float)dynui::kFsUnit)   == BL_SUCCESS &&
        fGrHero.create_from_face(InterMediumFace(),  (float)dynui::kFsGrHero) == BL_SUCCESS &&
        fTab   .create_from_face(InterMediumFace(),  (float)dynui::kFsTab)    == BL_SUCCESS &&
        fValue .create_from_face(InterMediumFace(),  (float)dynui::kFsValue)  == BL_SUCCESS;
  }
  // (re)create the offscreen image only when the device pixel size changes.
  bool ensureImage(int devW, int devH) {
    if (imgW != devW || imgH != devH) {
      if (img.create(devW, devH, BL_FORMAT_PRGB32) != BL_SUCCESS) return false;
      imgW = devW; imgH = devH;
    }
    return true;
  }
};

// --- lifecycle -------------------------------------------------------------

UiCanvas::UiCanvas() = default;   // out-of-line: Gfx is complete here (pimpl)

UiCanvas::~UiCanvas()
{
#ifdef _WIN32
  if (m_memBmp) { DeleteObject(m_memBmp); m_memBmp = nullptr; }
  if (m_memDC)  { DeleteDC(m_memDC); m_memDC = nullptr; }
#else
  if (m_memDC)  { SWELL_DeleteGfxContext(m_memDC); m_memDC = nullptr; }
#endif
}

bool UiCanvas::ensure(HDC hdc, int devW, int devH)
{
  if (devW < 1 || devH < 1) return false;
  if (m_memDC && m_w == devW && m_h == devH) return true;

  // [BUG, latent Linux skew - same root cause as forum #65] The platform surface
  // stride is NOT always its width: SWELL's Linux (LICE) backend pads the row
  // span to (w+4)&~4 (stride != width when w%8 is in {4..7}), while macOS
  // (rowbytes w*4) and Win32 32bpp DIBs have no padding. Allocate at a
  // multiple-of-8 width so stride == m_strideW on EVERY backend; presentSurface
  // writes rows at m_strideW and blits only the visible devW.
  const int strideW = (devW + 7) & ~7;

#ifdef _WIN32
  if (m_memBmp) { DeleteObject(m_memBmp); m_memBmp = nullptr; }
  if (m_memDC)  { DeleteDC(m_memDC); m_memDC = nullptr; }
  BITMAPINFO bmi = {};
  bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
  bmi.bmiHeader.biWidth = strideW;
  bmi.bmiHeader.biHeight = -devH; // top-down
  bmi.bmiHeader.biPlanes = 1;
  bmi.bmiHeader.biBitCount = 32;
  bmi.bmiHeader.biCompression = BI_RGB;
  void* bits = nullptr;
  m_memBmp = CreateDIBSection(hdc, &bmi, DIB_RGB_COLORS, &bits, nullptr, 0);
  if (!m_memBmp) return false;
  m_memDC = CreateCompatibleDC(hdc);
  if (!m_memDC) { DeleteObject(m_memBmp); m_memBmp = nullptr; return false; }
  SelectObject(m_memDC, m_memBmp);
#else
  if (m_memDC) { SWELL_DeleteGfxContext(m_memDC); m_memDC = nullptr; }
  m_memDC = SWELL_CreateMemContext(hdc, strideW, devH);
  if (!m_memDC) return false;
#endif
  m_w = devW;
  m_h = devH;
  m_strideW = strideW;
  return true;
}

// --- composable draw helpers (shared by the spike now; RenderPanel in Phase 2) -

// Transfer-curve plot inside the square well at (px0,py0,plotSide): well bg,
// unity diagonal, reduction wedge, dotted threshold, gate cliff, static curve,
// amber operating-point segment + glow dot, and input-axis dB tick labels.
// Drawn in logical coordinates; mirrors dynamics_engine ComputeCompression math.
static void DrawTransferPlot(BLContext& ctx, const Gfx& gfx,
                             double px0, double py0, double plotSide,
                             const DynCurveParams& p, int activeTab = 2)
{
  const double px1 = px0 + plotSide;
  const double py1 = py0 + plotSide;
  // Per-tab emphasis (design spec sec 6): the Compressor tab dims the gate, the Gate tab
  // dims the compressor, the View tab (2) lights both. The off-focus processor's coloured
  // elements (red comp wedge + comp threshold / violet gate cliff) drop to ~30% alpha so
  // the focused processor stands out; the neutral curve + operating point stay full.
  const double compA = (activeTab == 1) ? 0.30 : 1.0;   // dim compressor on the Gate tab
  const double gateA = (activeTab == 0) ? 0.30 : 1.0;   // dim gate on the Compressor tab
  ctx.fill_round_rect(BLRoundRect(px0, py0, plotSide, plotSide, dynui::kRadiusCtrl),
                      col(dynui::kSurface1));

  const double inMin = p.inMinDb, inMax = p.inMaxDb;
  const double span = (inMax - inMin) != 0 ? (inMax - inMin) : 1.0;
  auto dbToX = [&](double db) { return px0 + (db - inMin) / span * plotSide; };
  auto dbToY = [&](double db) { return py1 - (db - inMin) / span * plotSide; };

  // Curve math mirrors dynamics_engine ComputeCompression() steady state, INCLUDING
  // makeup: the plotted curve is the true output y = x + GR + makeup + gate (engine
  // :306), so the amber line rises with the Makeup knob and never lies about what
  // Apply does (the anti-slop "curve == Apply" rule). Makeup is a constant vertical
  // shift; the reduction wedge measures from the makeup baseline (x+makeup), so red
  // still = pure gain reduction. The unity diagonal stays as the 1:1 reference -
  // the gap between it and the curve at low input is the visible makeup boost.
  auto compGrDb = [&](double in) {
    return CompressionGrDb(in, p);   // <= 0 in Down; capped boost >= 0 in Up
  };
  auto gateGrDb = [&](double in, double compGr) -> double {
    if (!p.showGate) return 0.0;
    const double detect = (p.mode != 0) ? in : in + compGr;                  // Up/Both: raw; Down: post-comp, PRE-makeup
    if (detect >= p.gateThreshDb) return 0.0;
    const double gateRangeNeg = -std::fabs(p.gateRangeDb);                   // engine range is negative
    const double gateSlope = std::max(1.0, p.gateRatio) - 1.0;               // closed-state slope Rg-1
    return std::max(gateSlope * (detect - p.gateThreshDb), gateRangeNeg);    // ramp 0 -> range, clamped
  };
  auto compOut = [&](double in) { return in + compGrDb(in) + p.makeupDb; }; // wedge bottom: comp + makeup
  auto outAt   = [&](double in) { return CurveOutDb(in, p); };             // full output (shared w/ handles)

  // clip to the plot well so curves never spill over the rounded corners
  ctx.save();
  ctx.clip_to_rect(BLRect(px0, py0, plotSide, plotSide));

  // unity 1:1 diagonal (faint reference)
  ctx.set_stroke_width(1.0);
  ctx.stroke_line(BLLine(px0, py1, px1, py0), col(dynui::kCurveUnity));

  // Hysteresis band (v2.3.0 gate extension): with H < 0 the gate OPENS at tOpen
  // but stays open down to tClose = tOpen + H, so the instantaneous behaviour in
  // between is state-dependent - the faint violet band keeps the static plot
  // honest about that. The band lives in the DETECT domain; detect(x) = x +
  // compGR(x) is strictly increasing (comp slope > -1), so it inverts to an
  // input range by bisection. Dims with the gate on the Compressor tab.
  if (p.showGate && p.gateHystDb < 0.0) {
    // Detection domain mirrors the engine: Up gates on the RAW input (x axis).
    auto detectAt = [&](double in) { return (p.mode != 0) ? in : in + compGrDb(in); };
    auto invDetect = [&](double target) {
      double lo = inMin, hi = inMax;
      if (detectAt(lo) >= target) return lo;
      if (detectAt(hi) <= target) return hi;
      for (int it = 0; it < 24; ++it) {
        const double mid = 0.5 * (lo + hi);
        if (detectAt(mid) < target) lo = mid; else hi = mid;
      }
      return 0.5 * (lo + hi);
    };
    const double xC = dbToX(invDetect(p.gateThreshDb + p.gateHystDb));
    const double xO = dbToX(invDetect(p.gateThreshDb));
    if (xO - xC > 0.5)
      ctx.fill_rect(BLRect(xC, py0, xO - xC, plotSide),
                    colA(dynui::kGateViolet, (int)(30.0 * gateA)));
  }

  const int N = dynui::kPlotSamples;
  auto sampleDb = [&](int i) { return inMin + span * (double)i / (double)N; };

  // reduction wedge: area between the makeup baseline (x+makeup) and the COMPRESSION
  // curve (x+compGR+makeup; gate excluded so red = compression reduction only). The
  // gap equals -compGR regardless of makeup, so red stays = pure reduction.
  // Per-column vertical gradient from the makeup baseline (x+makeup, opaque) DOWN to the
  // compression curve (x+compGR+makeup, transparent) so the red fades to NOTHING exactly
  // at the curve - a single full-height gradient would be cut with a hard edge wherever
  // the curve crosses it mid-plot. Each thin strip's gradient is local to its own
  // baseline->curve span; adjacent strips share an edge (no overlap/seam). Columns with
  // no visible reduction are skipped. gap = -compGR = compression reduction (gate excluded).
  {
    const int topAlpha = (int)std::lround(70.0 * compA);
    for (int i = 0; i < N; ++i) {
      const double inA = sampleDb(i), inB = sampleDb(i + 1);
      const double xA = dbToX(inA), xB = dbToX(inB);
      const double baseA = dbToY(inA + p.makeupDb), baseB = dbToY(inB + p.makeupDb);
      const double curvA = dbToY(compOut(inA)), curvB = dbToY(compOut(inB));
      if (curvA - baseA < 0.5 && curvB - baseB < 0.5) continue;   // curve sits on the baseline -> no reduction
      BLPath strip;
      strip.move_to(xA, baseA); strip.line_to(xB, baseB);
      strip.line_to(xB, curvB); strip.line_to(xA, curvA); strip.close();
      BLGradient g(BLLinearGradientValues(0, 0.5 * (baseA + baseB), 0, 0.5 * (curvA + curvB)));
      g.add_stop(0.0, colA(dynui::kGrRed, topAlpha));   // opaque at the makeup baseline
      g.add_stop(1.0, colA(dynui::kGrRed, 0));          // transparent at the curve (soft edge)
      ctx.fill_path(strip, g);
    }
  }

  // dotted threshold line (vertical), persists regardless of overlays
  {
    const double tx = dbToX(p.thresholdDb);
    ctx.set_stroke_width(1.0);
    for (double yy = py0; yy < py1; yy += 5.0)
      ctx.stroke_line(BLLine(tx, yy, tx, std::min(yy + 2.5, py1)),
                      colA(dynui::kInkMuted, (int)std::lround(200.0 * compA)));
  }

  // static transfer curve (neutral), full shape including the gate drop
  BLPath curve;
  for (int i = 0; i <= N; ++i) {
    const double in = sampleDb(i);
    const double cx = dbToX(in), cy = dbToY(outAt(in));
    if (i == 0) curve.move_to(cx, cy); else curve.line_to(cx, cy);
  }
  ctx.set_stroke_width(2.0);
  ctx.stroke_path(curve, col(dynui::kCurveStatic));

  // gate cliff: re-stroke the input subrange where the gate is active, in violet.
  // Onset is at input where the post-comp (pre-makeup) level crosses gateThresh - i.e.
  // input == gateThresh while below the comp knee - so the gate node at input=gateThresh
  // sits on the cliff regardless of makeup (makeup only lifts the whole curve). Depth
  // ramps to the gate range + clamps. Drawn ON the curve (outAt) so it stays continuous.
  if (p.showGate) {
    BLPath gate;
    bool started = false;
    for (int i = 0; i <= N; ++i) {
      const double in = sampleDb(i);
      if (gateGrDb(in, compGrDb(in)) < 0.0) {
        const double cx = dbToX(in), cy = dbToY(outAt(in));
        if (!started) { gate.move_to(cx, cy); started = true; } else gate.line_to(cx, cy);
      }
    }
    if (started) {
      ctx.set_stroke_width(2.0);
      ctx.stroke_path(gate, colA(dynui::kGateViolet, (int)std::lround(255.0 * gateA)));
    }
  }

  // live segment up to the operating point (avgPeak), amber + glow
  const bool hasOp = p.avgPeakDb > inMin && p.avgPeakDb <= inMax;
  if (hasOp) {
    BLPath lit;
    bool started = false;
    for (int i = 0; i <= N; ++i) {
      const double in = sampleDb(i);
      if (in > p.avgPeakDb) break;
      const double cx = dbToX(in), cy = dbToY(outAt(in));
      if (!started) { lit.move_to(cx, cy); started = true; } else lit.line_to(cx, cy);
    }
    lit.line_to(dbToX(p.avgPeakDb), dbToY(outAt(p.avgPeakDb)));
    GlowStroke(ctx, lit, dynui::kAmberGlow);
    ctx.set_stroke_width(2.0);
    ctx.stroke_path(lit, col(dynui::kAmber));

    // operating-point dot + glow
    const double dx = dbToX(p.avgPeakDb), dy = dbToY(outAt(p.avgPeakDb));
    ctx.set_comp_op(BL_COMP_OP_PLUS);
    ctx.fill_circle(BLCircle(dx, dy, 7.0), colA(dynui::kAmberGlow, 60));
    ctx.fill_circle(BLCircle(dx, dy, 4.5), colA(dynui::kAmberGlow, 110));
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
    ctx.fill_circle(BLCircle(dx, dy, 3.0), col(dynui::kAmber));
  }

  ctx.restore();   // remove plot clip

  // input-axis dB tick labels on a 12 dB grid within [inMin, inMax]
  if (gfx.fontsReady) {
    const BLFont& f = gfx.fTick;
    const double step = (double)dynui::kTickStepDb;
    for (double db = std::ceil(inMin / step) * step; db <= inMax + 0.001; db += step) {
      char buf[8];
      std::snprintf(buf, sizeof(buf), "%d", (int)std::lround(db));
      ctx.fill_utf8_text(BLPoint(dbToX(db) + 2.0, py1 + 11.0), f, buf,
                         SIZE_MAX, col(dynui::kInkMuted));
    }
  }
}

// GR meter to the right of the plot (anchored at px1): track + downward red fill
// + ticks + peak-hold marker + hero numeric readout. (must-dos #2/#3 refine the
// value + scale at Inc 2; this is the verbatim spike behaviour.)
static void DrawGrMeter(BLContext& ctx, const Gfx& gfx,
                        double px1, double py0, double plotSide,
                        const DynCurveParams& p, bool withNumber = true)
{
  // Value = real engine average GR (p.avgGrDb, negative) -> magnitude: the truthful
  // applied/average GR (what auto-makeup compensated, what Apply does). Scale = the
  // PLOT's px-per-dB so the fill height equals the curve-to-diagonal gap (must-do
  // #2: shared scale, not a private 24 dB range).
  const double span = (p.inMaxDb - p.inMinDb) != 0 ? (p.inMaxDb - p.inMinDb) : 1.0;
  const double pxPerDb = plotSide / span;
  // Up mode: avgGrDb goes POSITIVE (boost) - same bar geometry, amber fill
  // (user-locked 2026-07-02); Down keeps the red reduction fill.
  const bool boost = p.avgGrDb > 0.0;
  const double grMag = boost ? p.avgGrDb : std::max(0.0, -p.avgGrDb);
  const uint32_t fillCol = boost ? dynui::kAmber : dynui::kGrRed;
  const double meterX = px1 + (double)dynui::kMeterGap;
  const double barW = (double)dynui::kMeterBarW;
  const double barTop = py0;
  const double barH = plotSide;

  ctx.fill_round_rect(BLRoundRect(meterX, barTop, barW, barH, 4.0),
                      col(dynui::kSurface2));
  const double fillH = std::clamp(grMag * pxPerDb, 0.0, barH);
  if (fillH > 0.5) {
    BLGradient g(BLLinearGradientValues(0, barTop, 0, barTop + barH));
    g.add_stop(0.0, col(fillCol));
    g.add_stop(1.0, colA(fillCol, 120));
    ctx.fill_round_rect(BLRoundRect(meterX, barTop, barW, fillH, 4.0), g);
    ctx.fill_rect(BLRect(meterX, barTop + fillH - 1.0, barW, 2.0),
                  col(dynui::kAmberGlow));   // peak-hold marker
  }
  const double ticks[] = { 0.0, 3.0, 6.0, 12.0, 24.0 };
  ctx.set_stroke_width(1.0);
  for (double t : ticks) {
    const double ty = barTop + std::clamp(t * pxPerDb, 0.0, barH);
    ctx.stroke_line(BLLine(meterX - 3.0, ty, meterX, ty), colA(dynui::kInkMuted, 200));
  }

  // Numeric hero column (spike layout). The premium panel passes withNumber=false
  // and renders the GR hero number in the header instead (compact grid needs the
  // body width for the knob grid).
  if (withNumber && gfx.fontsReady) {
    const double numX = meterX + barW + (double)dynui::kMeterNumGap;
    char num[16];
    std::snprintf(num, sizeof(num), "%.1f", grMag);
    ctx.fill_utf8_text(BLPoint(numX, barTop + 13.0), gfx.fLabel, "GR", SIZE_MAX,
                       col(dynui::kInkSecondary));
    ctx.fill_utf8_text(BLPoint(numX, barTop + 40.0), gfx.fGrHero, num, SIZE_MAX,
                       col(dynui::kGrRed));
    const double numAdvance = TextWidth(gfx.fGrHero, num);
    ctx.fill_utf8_text(BLPoint(numX + numAdvance + 5.0, barTop + 40.0), gfx.fUnit, "dB",
                       SIZE_MAX, col(dynui::kInkMuted));
  }
}

// --- knob grid (Inc 4) -----------------------------------------------------

// Param index -> (tab, column, row) in the compact knob grid. Tab 0=Compressor
// (DYNAMICS column 0: Thresh/Ratio/Knee/Makeup; TIME column 1: Attack/Release/
// L.ahead), tab 1=Gate (G.Thr/G.Range/G.Hold), tab 2=View (no knobs). Matches the
// SLIDER_DEFS order in dynamics_panel.cpp. The single IA source for render + hit.
struct KnobSlot { int tab, col, row; };
static const KnobSlot KNOB_SLOTS[kDynNumParams] = {
  { 0, 0, 0 },  // 0  Thresh   (Compressor / DYNAMICS)
  { 0, 0, 1 },  // 1  Ratio
  { 0, 0, 2 },  // 2  Knee
  { 0, 1, 0 },  // 3  Attack   (Compressor / TIME)
  { 0, 1, 1 },  // 4  Release
  { 0, 0, 3 },  // 5  Makeup   (Compressor / DYNAMICS)
  { 0, 1, 2 },  // 6  L.ahead  (Compressor / TIME)
  { 1, 0, 0 },  // 7  G.Thr    (Gate / LEVELS - mirrors the Compressor tab IA)
  { 1, 0, 2 },  // 8  G.Range
  { 1, 1, 2 },  // 9  G.Hold   (Gate / TIME)
  { 1, 0, 1 },  // 10 G.Ratio  (Gate / LEVELS)
  { 1, 0, 3 },  // 11 G.Hyst
  { 1, 1, 0 },  // 12 G.Att    (Gate / TIME)
  { 1, 1, 1 },  // 13 G.Rel
  { 0, 1, 3 },  // 14 M.Boost  (Compressor; ex-RMS cell - RMS moved to the footer; Up mode only)
};

// Compact-mode slots: the hero plot is hidden, so the knobs reflow into a wider
// 4-col x 2-row grid filling the full body width. Compressor row0 = Thresh/Ratio/
// Knee/Makeup, row1 = Attack/Release/L.ahead (+ Peak/RMS in col3); Gate row0 = the
// three gate knobs. Same param indices as KNOB_SLOTS, different cell positions.
static const KnobSlot COMPACT_KNOB_SLOTS[kDynNumParams] = {
  { 0, 0, 0 },  // 0  Thresh
  { 0, 1, 0 },  // 1  Ratio
  { 0, 2, 0 },  // 2  Knee
  { 0, 0, 1 },  // 3  Attack
  { 0, 1, 1 },  // 4  Release
  { 0, 3, 0 },  // 5  Makeup
  { 0, 2, 1 },  // 6  L.ahead
  { 1, 0, 0 },  // 7  G.Thr    (row0 = levels, row1 = time)
  { 1, 2, 0 },  // 8  G.Range
  { 1, 2, 1 },  // 9  G.Hold
  { 1, 1, 0 },  // 10 G.Ratio
  { 1, 3, 0 },  // 11 G.Hyst
  { 1, 0, 1 },  // 12 G.Att
  { 1, 1, 1 },  // 13 G.Rel
  { 0, 3, 1 },  // 14 M.Boost  (ex-RMS compact cell; Up mode only)
};

static inline double Deg2Rad(double d) { return d * 3.14159265358979323846 / 180.0; }

// One knob in its cell: arc track (270deg) + value fill arc + center cap +
// indicator line + default-value tick on the ring, with the UPPERCASE label and
// value/unit text in a column to the right. Gate knobs fill violet, others amber.
static void DrawKnob(BLContext& ctx, const Gfx& gfx, const URect& cell, const KnobVM& k)
{
  if (cell.w < 1.0) return;   // not on the active tab
  const double dia = (double)dynui::kKnobDiaSm;
  const double r   = dia * 0.5;
  const double cx  = cell.x + 2.0 + r;
  const double cy  = cell.y + cell.h * 0.5;
  const double a0  = Deg2Rad(dynui::kKnobArcStartDeg);
  const double sw  = Deg2Rad(dynui::kKnobArcSweepDeg);
  const double norm = std::clamp(k.norm, 0.0, 1.0);
  const uint32_t fillCol = k.isGate ? dynui::kGateViolet : dynui::kAmber;

  // hover/drag: soft additive glow around the ring (the track + fill draw on top,
  // crisp, with the glow bleeding outside) - the "adjustable" affordance cue.
  if (k.hover) {
    ctx.set_comp_op(BL_COMP_OP_PLUS);
    BLPath ring; ring.arc_to(cx, cy, r, r, a0, sw, true);
    ctx.set_stroke_width(7.0); ctx.stroke_path(ring, colA(fillCol, 22));
    ctx.set_stroke_width(4.0); ctx.stroke_path(ring, colA(fillCol, 32));
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
  }

  // ring track (full sweep)
  ctx.set_stroke_width(3.0);
  { BLPath p; p.arc_to(cx, cy, r, r, a0, sw, true); ctx.stroke_path(p, col(dynui::kSurface2)); }
  // value fill (start -> norm)
  if (norm > 0.001) {
    BLPath p; p.arc_to(cx, cy, r, r, a0, sw * norm, true);
    ctx.stroke_path(p, col(fillCol));
  }
  // center cap (faint depth)
  ctx.fill_circle(BLCircle(cx, cy, r - 4.5), col(dynui::kSurface3));
  // indicator line at the current angle
  {
    const double a = a0 + sw * norm;
    ctx.set_stroke_width(2.0);
    ctx.stroke_line(BLLine(cx + std::cos(a) * (r - 12.0), cy + std::sin(a) * (r - 12.0),
                           cx + std::cos(a) * (r - 3.0),  cy + std::sin(a) * (r - 3.0)),
                    col(fillCol));
  }
  // default-value tick notch just outside the ring
  {
    const double a = a0 + sw * std::clamp(k.defaultNorm, 0.0, 1.0);
    const double r0 = r + 1.0, r1 = r + 1.0 + (double)dynui::kDefaultTickLen;
    ctx.set_stroke_width(1.0);
    ctx.stroke_line(BLLine(cx + std::cos(a) * r0, cy + std::sin(a) * r0,
                           cx + std::cos(a) * r1, cy + std::sin(a) * r1),
                    colA(dynui::kInkMuted, 200));
  }
  // label + value text column to the right of the knob
  if (gfx.fontsReady) {
    const double tx = cell.x + dia + (double)dynui::kKnobTextGap;
    char up[24];
    int n = 0;
    for (const char* s = k.label ? k.label : ""; *s && n < (int)sizeof(up) - 1; ++s)
      up[n++] = (char)std::toupper((unsigned char)*s);
    up[n] = '\0';
    ctx.fill_utf8_text(BLPoint(tx, cy - 3.0), gfx.fLabel, up, SIZE_MAX, col(dynui::kInkSecondary));

    const double vy = cy + 15.0;
    if (k.editing) {
      // Inline type-value editor (Inc 8): a surface3 box with an amber outline holds
      // the live text + a solid amber caret, replacing the readout. The knob arc still
      // shows the OLD value so the change is visible until committed. The box spans the
      // readout column (tx -> cell right) so typical entries ("1000", "-18.5") fit.
      const char* et = k.editText ? k.editText : "";
      const double boxX = std::max(cell.x, tx - 3.0);          // never spill left of the cell
      const double boxW = std::max(0.0, cell.x + cell.w - boxX); // ...nor past its right edge
      const double boxY = vy - 13.0, boxH = 18.0;
      ctx.fill_round_rect(BLRoundRect(boxX, boxY, boxW, boxH, dynui::kRadiusCtrl),
                          col(dynui::kSurface3));
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(boxX + 0.5, boxY + 0.5, boxW - 1.0, boxH - 1.0,
                                        dynui::kRadiusCtrl), col(dynui::kAmber));
      // Clip text + caret to the box so an over-long entry can't bleed past the edge.
      ctx.save();
      ctx.clip_to_rect(BLRect(boxX, boxY, boxW, boxH));
      ctx.fill_utf8_text(BLPoint(tx, vy), gfx.fValue, et, SIZE_MAX, col(dynui::kInkPrimary));
      if (k.caretOn) {   // blink (motion pass): solid right after a keystroke, then ~1s on/off
        const double caretX = tx + TextWidth(gfx.fValue, et) + 1.0;
        ctx.fill_rect(BLRect(caretX, vy - 11.0, 1.6, 14.0), col(dynui::kAmber));
      }
      ctx.restore();
    } else {
      // Value number (16px primary) + unit (11px muted) on its own advance, per the
      // type spec - keeps long readouts ("1000 ms") inside the content margin and lets
      // ":1" abut the number. Auto-makeup shows the computed value with a muted "auto".
      // showOff (G.Thr at the sentinel / hard-left detent) renders "Off", no unit;
      // showInf (Ratio at the Inf:1 sentinel) renders "Inf:1".
      char num[24];
      if (k.showOff) std::snprintf(num, sizeof(num), "Off");
      else if (k.showInf) std::snprintf(num, sizeof(num), "Inf");
      else std::snprintf(num, sizeof(num), k.precision == 1 ? "%.1f" : "%.0f", k.value);
      ctx.fill_utf8_text(BLPoint(tx, vy), gfx.fValue, num, SIZE_MAX, col(dynui::kInkPrimary));
      const char* unit = k.showOff ? "" : (k.showAuto ? "auto" : (k.unit ? k.unit : ""));
      if (*unit) {
        const bool abut = (unit[0] == ':');   // ratio ":1" sits flush against the number
        const double ux = tx + TextWidth(gfx.fValue, num) + (abut ? 1.0 : 4.0);
        ctx.fill_utf8_text(BLPoint(ux, vy), gfx.fUnit, unit, SIZE_MAX, col(dynui::kInkMuted));
      }
    }
  }
}

// Ensure the platform surface + cached BLImage/fonts are ready at devW x devH.
bool UiCanvas::prepareSurface(HDC hdc, int devW, int devH)
{
  if (!ensure(hdc, devW, devH)) return false;
  if (!m_gfx) m_gfx = std::make_unique<Gfx>();
  m_gfx->ensureFonts();
  return m_gfx->ensureImage(devW, devH);
}

// Copy the rendered BLImage scanlines into the platform framebuffer (forcing
// opaque alpha), then scaled-blit to the destination DC. dpr==1 -> devW==w -> 1:1
// (Windows/Linux unchanged); dpr>1 onto the real Retina window DC -> SWELL maps
// the 2x source onto the 2x backing => crisp HiDPI. (Plain BitBlt(devW,devH) would
// place device-sized px at a logical position = 2x-too-large; the BitBlt-1:1 trap
// documented in .harness/design_phase2_architecture.md.)
void UiCanvas::presentSurface(HDC hdc, int x, int y, int w, int h, int devW, int devH)
{
  unsigned int* fbuf = nullptr;
#ifdef _WIN32
  BITMAP bm;
  if (GetObject(m_memBmp, sizeof(bm), &bm)) fbuf = (unsigned int*)bm.bmBits;
#else
  fbuf = (unsigned int*)SWELL_GetCtxFrameBuffer(m_memDC);
#endif
  if (!fbuf) return;

  BLImageData dat;
  if (m_gfx->img.get_data(&dat) != BL_SUCCESS) return;
  if (!dat.pixel_data) return;
  if (dat.stride <= 0 || (dat.stride % 4) != 0 || dat.stride < (intptr_t)devW * 4) return;
  const uint8_t* srcBase = (const uint8_t*)dat.pixel_data;
  // Dest rows advance by the REAL surface stride (m_strideW, alignment-padded in
  // ensure()) - never by devW, which shears on the Linux LICE backend (see ensure).
  for (int row = 0; row < devH; ++row) {
    const unsigned int* s = (const unsigned int*)(srcBase + (intptr_t)row * dat.stride);
    unsigned int* d = fbuf + (size_t)row * (size_t)m_strideW;
    for (int col2 = 0; col2 < devW; ++col2)
      d[col2] = s[col2] | 0xFF000000u;
  }
  StretchBlt(hdc, x, y, w, h, m_memDC, 0, 0, devW, devH, SRCCOPY);
}

// --- panel layout + chrome (Inc 3b) ----------------------------------------

DynLayout ComputeDynLayout(double w, double h, int activeTab, bool compact)
{
  DynLayout L;
  const double pad = dynui::kPanelPad;
  L.header = { 0, 0, w, (double)dynui::kHeaderH };
  L.footer = { 0, h - (double)dynui::kFooterH, w, (double)dynui::kFooterH };

  const double hMid = L.header.h * 0.5;
  L.closeBtn = { w - pad - 18.0, hMid - 9.0, 18.0, 18.0 };
  L.abBtn    = { L.closeBtn.x - 48.0, hMid - 11.0, 40.0, 22.0 };
  // Preset box narrowed 120 -> 96 (v2.3.0) to make room for the mode button;
  // the preset name is CLIPPED to the box when it renders (long names ellipse
  // visually instead of spilling into the neighbours).
  L.preset   = { pad + 96.0, hMid - 11.0, 96.0, 22.0 };
  // DOWN/UP processor-mode STATE BUTTON (v2.3.0): header chrome right of the
  // preset box - it switches the whole gain computer, not a tab-local control.
  // A/B-style (shows the current mode, click flips). Header width budget at
  // kPanelW 480 is exact: the BOOST readout's caption is skipped by DrawHeader
  // if it would still touch this button (worst-case '+24.0' at kFsGrHero).
  L.modeBtn = { L.preset.x + L.preset.w + 8.0, hMid - 11.0, 48.0, 22.0 };

  const double bodyTop = L.header.h;
  const double bodyH = L.footer.y - bodyTop;

  if (compact) {
    // Compact mode: the hero plot + GR meter are hidden (the on-waveform overlay is
    // the visual); the knobs reflow into a wider 4-col x 2-row grid filling the body.
    L.plotWell = { 0, 0, 0, 0 };
    L.grMeter  = { 0, 0, 0, 0 };
    const int COLS = 4, ROWS = 2;
    const double gridX = pad, gridR = w - pad;
    const double colGap = (double)dynui::kKnobColGap;
    const double cCellW = (gridR - gridX - colGap * (COLS - 1)) / (double)COLS;
    const double gridTop = bodyTop + 8.0;
    const double cCellH = ((L.footer.y - 8.0) - gridTop) / (double)ROWS;
    auto ccell = [&](int ccol, int crow) -> URect {
      return { gridX + (double)ccol * (cCellW + colGap), gridTop + (double)crow * cCellH,
               cCellW, cCellH };
    };
    for (int i = 0; i < kDynNumParams; ++i) {
      const KnobSlot& s = COMPACT_KNOB_SLOTS[i];
      L.knob[i] = (s.tab == activeTab) ? ccell(s.col, s.row) : URect{ 0, 0, 0, 0 };
    }
    // Peak/RMS moved to the footer gap (v2.3.0) - M.Boost owns the ex-RMS cell.
    if (activeTab == 2) {   // View: DYN/ENV/GR/LIVE on row0; Compact on row1
      const double tH = 36.0;
      auto pill = [&](int ccol, int crow) -> URect {
        const URect c = ccell(ccol, crow); return { c.x, c.y + (c.h - tH) * 0.5, c.w, tH };
      };
      L.viewToggle[0] = pill(0, 0);  // DYN
      L.viewToggle[1] = pill(1, 0);  // ENV
      L.viewToggle[2] = pill(2, 0);  // GR
      L.viewToggle[3] = pill(3, 0);  // LIVE
      L.compactToggle = pill(0, 1);  // COMPACT
      // No A/B (it lives in the header) and no meter-scale (the plot + GR meter it
      // scales are hidden in compact, so the selector would do nothing).
    }
  } else {
  // Hero transfer plot: square on the LEFT, sized to the body height. The GR meter
  // is a bar-only column right of it (the hero number lives in the header for this
  // compact grid). The remaining width on the right holds the 2-col knob grid.
  const double plotSide = std::max(40.0, std::min(bodyH - 2.0 * pad, (w - 2.0 * pad) * 0.40));
  const double bodyMid = bodyTop + bodyH * 0.5;
  L.plotWell = { pad, bodyMid - plotSide * 0.5, plotSide, plotSide };
  L.grMeter  = { L.plotWell.x + plotSide + (double)dynui::kMeterGap, L.plotWell.y,
                 (double)dynui::kMeterBarW, plotSide };

  // Knob grid: kKnobCols x kKnobRows cells filling the band right of the meter,
  // vertically aligned with the plot. Each param maps to a (tab,col,row) slot;
  // off-tab params get an empty rect so render + hit-test both skip them.
  const double gridX = L.grMeter.x + L.grMeter.w + (double)dynui::kKnobGridGap;
  const double gridR = w - pad;
  const double colGap = (double)dynui::kKnobColGap;
  const double cellW = (gridR - gridX - colGap * (dynui::kKnobCols - 1)) / (double)dynui::kKnobCols;
  const double cellH = plotSide / (double)dynui::kKnobRows;
  auto cellRect = [&](int ccol, int crow) -> URect {
    return { gridX + (double)ccol * (cellW + colGap), L.plotWell.y + (double)crow * cellH,
             cellW, cellH };
  };
  for (int i = 0; i < kDynNumParams; ++i) {
    const KnobSlot& s = KNOB_SLOTS[i];
    L.knob[i] = (s.tab == activeTab) ? cellRect(s.col, s.row) : URect{ 0, 0, 0, 0 };
  }

  // Peak/RMS moved to the footer gap (v2.3.0) - M.Boost owns the ex-RMS cell.
  // View-tab state toggles fill the knob-grid cells: col0 rows 0-2 = Dyn/Env/GR
  // (overlay visibility), col1 row0 = Live, col1 row1 = Compact. (A/B is NOT here -
  // it lives in the header.) The meter-scale selector spans the bottom row.
  if (activeTab == 2) {
    static const int slot[4][2] = { {0,0}, {0,1}, {0,2}, {1,0} };  // DYN/ENV/GR/LIVE
    const double tH = 36.0;
    for (int i = 0; i < 4; ++i) {
      const URect c = cellRect(slot[i][0], slot[i][1]);
      L.viewToggle[i] = { c.x, c.y + (c.h - tH) * 0.5, c.w, tH };
    }
    // Compact-mode toggle: col1 row1 (below Live).
    const URect cc = cellRect(1, 1);
    L.compactToggle = { cc.x, cc.y + (cc.h - tH) * 0.5, cc.w, tH };
    // Meter-scale selector: a 4-segment dB-floor control on the bottom grid row,
    // spanning both columns. A "SCALE" caption (render-only) sits in the left gutter.
    const URect c0 = cellRect(0, 3), c1 = cellRect(1, 3);
    const double segH = 24.0, segGap = 2.0, capW = 44.0;
    const double segY = c0.y + (c0.h - segH) * 0.5;
    const double x0 = c0.x + capW, right = c1.x + c1.w;
    const int nSeg = dynui::kMeterFloorOptCount;
    const double segW = (right - x0 - (double)(nSeg - 1) * segGap) / (double)nSeg;
    for (int i = 0; i < nSeg; ++i)
      L.meterScale[i] = { x0 + (double)i * (segW + segGap), segY, segW, segH };
  }
  }

  const double fMid = L.footer.y + L.footer.h * 0.5;
  L.apply = { pad, fMid - 12.0, 84.0, 24.0 };
  const double segW = 86.0, segGap = 2.0;
  const double pillW = 3.0 * segW + 2.0 * segGap;
  const double pillX = w - pad - pillW;
  for (int i = 0; i < 3; ++i)
    L.tabSeg[i] = { pillX + (double)i * (segW + segGap), fMid - 12.0, segW, 24.0 };
  // Stage-power dots (v2.3.0 INC-4): a small bypass toggle INSIDE the COMP and
  // GATE pills (left edge; the rest of the pill still switches tabs) - visible
  // in every layout mode, tied visually to its stage.
  for (int i = 0; i < 2; ++i)
    L.stagePower[i] = { L.tabSeg[i].x + 4.0, L.tabSeg[i].y + 4.0, 16.0, 16.0 };
  // Peak/RMS detection pill (v2.3.0: moved here from the knob grid so M.Boost
  // could take that cell): centred in the footer gap between Apply and the tab
  // pill. Compressor tab only - detection mode pairs with the comp controls.
  if (activeTab == 0) {
    const double rmsSegW = 44.0, rmsH = 24.0;
    const double gapL = L.apply.x + L.apply.w, gapR = pillX;
    const double rx = gapL + ((gapR - gapL) - 2.0 * rmsSegW - 2.0) * 0.5;
    L.rms[0] = { rx,                  fMid - rmsH * 0.5, rmsSegW, rmsH };
    L.rms[1] = { rx + rmsSegW + 2.0,  fMid - rmsH * 0.5, rmsSegW, rmsH };
  }

  // Free-resize grip: bottom-right corner. Sits in the right pad margin, just past
  // the tab pill's right edge (w - pad), so it never overlaps the VIEW segment.
  L.resizeGrip = { w - 16.0, h - 16.0, 16.0, 16.0 };
  return L;
}

void ComputeCurveHandles(const URect& pw, const DynCurveParams& p, int activeTab, URect out[2])
{
  out[0] = URect{ 0, 0, 0, 0 };
  out[1] = URect{ 0, 0, 0, 0 };
  if (pw.w < 1.0 || pw.h < 1.0) return;   // no plot well (Compact mode) -> no handles
  const double span = (p.inMaxDb - p.inMinDb) != 0.0 ? (p.inMaxDb - p.inMinDb) : 1.0;
  auto dbToX = [&](double db) { return pw.x + (db - p.inMinDb) / span * pw.w; };
  auto dbToY = [&](double db) { return pw.y + pw.h - (db - p.inMinDb) / span * pw.h; };
  const double R = 13.0;                                  // hit radius (base px)
  const double inset = 6.0;                               // keep the ~5.5px disc inside the well
  auto box = [&](double db) -> URect {
    double cx = std::clamp(dbToX(db), pw.x + inset, pw.x + pw.w - inset);
    double cy = std::clamp(dbToY(CurveOutDb(db, p)), pw.y + inset, pw.y + pw.h - inset);
    return URect{ cx - R, cy - R, 2.0 * R, 2.0 * R };
  };
  if (activeTab == 0)                    out[0] = box(p.thresholdDb);   // knee handle (always)
  else if (activeTab == 1 && p.showGate) out[1] = box(p.gateThreshDb);  // gate node only when gate on
}

static void FillURound(BLContext& ctx, const URect& r, double rad, uint32_t argb) {
  ctx.fill_round_rect(BLRoundRect(r.x, r.y, r.w, r.h, rad), col(argb));
}

// Horizontally-centered text within rect r (approx vertical centering).
static void TextCentered(BLContext& ctx, const BLFont& f, const URect& r,
                         const char* s, uint32_t argb) {
  const double tw = TextWidth(f, s);
  ctx.fill_utf8_text(BLPoint(r.x + (r.w - tw) * 0.5, r.y + r.h * 0.5 + 4.0), f, s,
                     SIZE_MAX, col(argb));
}

static void DrawSegmentedN(BLContext& ctx, const Gfx& gfx, const URect* segs,
                           const char* const* labels, int n, int activeIdx);

static void DrawHeader(BLContext& ctx, const Gfx& gfx, const DynLayout& L, const DynPanelVM& vm) {
  if (gfx.fontsReady) {
    ctx.fill_utf8_text(BLPoint(dynui::kPanelPad, L.header.h * 0.5 + 5.0), gfx.fValue,
                       "DYNAMICS", SIZE_MAX, col(dynui::kInkPrimary));
    FillURound(ctx, L.preset, dynui::kRadiusCtrl, dynui::kSurface2);
    ctx.save();   // clip long preset names to the (narrowed) box
    ctx.clip_to_rect(BLRect(L.preset.x, L.preset.y, L.preset.w - 4.0, L.preset.h));
    ctx.fill_utf8_text(BLPoint(L.preset.x + 8.0, L.preset.y + L.preset.h * 0.5 + 4.0),
                       gfx.fLabel, vm.presetName ? vm.presetName : "Preset", SIZE_MAX,
                       col(dynui::kInkSecondary));
    ctx.restore();

    // DOWN/UP processor-mode state button (v2.3.0 upward compression):
    // A/B-pattern - neutral "DOWN" at rest, amber outline + "UP" when engaged.
    const bool modeHot = (vm.mode != 0);
    FillURound(ctx, L.modeBtn, dynui::kRadiusCtrl, modeHot ? dynui::kSurface3 : dynui::kSurface2);
    if (modeHot) {
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(L.modeBtn.x + 0.5, L.modeBtn.y + 0.5,
                                        L.modeBtn.w - 1.0, L.modeBtn.h - 1.0, dynui::kRadiusCtrl),
                            col(dynui::kAmber));
    }
    static const char* const kModeTxt[3] = { "DOWN", "UP", "BOTH" };
    TextCentered(ctx, gfx.fLabel, L.modeBtn, kModeTxt[vm.mode < 0 || vm.mode > 2 ? 0 : vm.mode],
                 modeHot ? dynui::kAmber : dynui::kInkSecondary);

    // GR hero readout, right-aligned left of the A/B button - the load-bearing
    // number from the engine average GR (truthful applied GR). In Up mode the
    // average goes positive: caption "BOOST", "+x.x", amber (user-locked).
    const bool boost = vm.curve.avgGrDb > 0.0;
    char num[16];
    std::snprintf(num, sizeof(num), boost ? "+%.1f" : "%.1f",
                  boost ? vm.curve.avgGrDb : std::max(0.0, -vm.curve.avgGrDb));
    const char* grLbl = boost ? "BOOST" : "GR";
    const double unitW = TextWidth(gfx.fUnit, "dB");
    const double numW  = TextWidth(gfx.fGrHero, num);
    const double lblW  = TextWidth(gfx.fLabel, grLbl);
    const double xR    = L.abBtn.x - 10.0;
    const double unitX = xR - unitW;
    const double numX  = unitX - 4.0 - numW;
    const double lblX  = numX - 6.0 - lblW;
    const double baseY = L.header.h * 0.5 + 7.0;
    // Hard no-overlap guarantee: the caption is dropped (number + unit keep
    // their place, the amber '+' still reads as boost) if it would touch the
    // mode button - the header budget at kPanelW is exact at '+24.0'.
    if (lblX >= L.modeBtn.x + L.modeBtn.w + 6.0)
      ctx.fill_utf8_text(BLPoint(lblX,  baseY), gfx.fLabel,  grLbl, SIZE_MAX, col(dynui::kInkSecondary));
    ctx.fill_utf8_text(BLPoint(numX,  baseY), gfx.fGrHero, num,  SIZE_MAX,
                       col(boost ? dynui::kAmber : dynui::kGrRed));
    ctx.fill_utf8_text(BLPoint(unitX, baseY), gfx.fUnit,   "dB", SIZE_MAX, col(dynui::kInkMuted));

    // A/B bypass: reflects state (amber outline + "BYP" when bypassed) so the
    // always-visible header control reads the current compare state at a glance.
    const bool byp = vm.bypassed;
    FillURound(ctx, L.abBtn, dynui::kRadiusCtrl, byp ? dynui::kSurface3 : dynui::kSurface2);
    if (byp) {
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(L.abBtn.x + 0.5, L.abBtn.y + 0.5,
                                        L.abBtn.w - 1.0, L.abBtn.h - 1.0, dynui::kRadiusCtrl),
                            col(dynui::kAmber));
    }
    TextCentered(ctx, gfx.fLabel, L.abBtn, byp ? "BYP" : "A/B",
                 byp ? dynui::kAmber : dynui::kInkSecondary);
    TextCentered(ctx, gfx.fValue, L.closeBtn, "x", dynui::kInkMuted);
  }
  ctx.set_stroke_width(1.0);
  ctx.stroke_line(BLLine(0, L.header.h, L.header.w, L.header.h), col(dynui::kHairline));
}

static void DrawTabBar(BLContext& ctx, const Gfx& gfx, const DynLayout& L,
                       int activeTab, int tabFrom, double slideT,
                       bool compBypass, bool gateBypass) {
  const char* labels[3] = { "COMP", "GATE", "VIEW" };
  // inactive backgrounds first
  for (int i = 0; i < 3; ++i)
    FillURound(ctx, L.tabSeg[i], dynui::kRadiusCtrl, dynui::kSurface1);
  // one active fill + amber underline that GLIDES between segments (motion pass); at
  // slideT==1 it sits exactly on tabSeg[activeTab] (byte-identical to the static layout).
  {
    const URect& a = L.tabSeg[tabFrom < 0 || tabFrom > 2 ? activeTab : tabFrom];
    const URect& b = L.tabSeg[activeTab];
    const double t = std::clamp(slideT, 0.0, 1.0);
    const URect s{ a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t,
                   a.w + (b.w - a.w) * t, a.h + (b.h - a.h) * t };
    FillURound(ctx, s, dynui::kRadiusCtrl, dynui::kSurface3);
    ctx.fill_rect(BLRect(s.x + 6.0, s.y + s.h - 2.0, s.w - 12.0, 2.0), col(dynui::kAmber));
  }
  // labels: the destination tab is amber immediately; the fill catches up underneath
  if (gfx.fontsReady)
    for (int i = 0; i < 3; ++i)
      TextCentered(ctx, gfx.fTab, L.tabSeg[i], labels[i],
                   i == activeTab ? dynui::kAmber : dynui::kInkSecondary);
  // Stage-power dots: filled amber ring = stage active, hollow grey = bypassed.
  const bool byp[2] = { compBypass, gateBypass };
  for (int i = 0; i < 2; ++i) {
    const URect& d = L.stagePower[i];
    const double cx = d.x + d.w * 0.5, cy = d.y + d.h * 0.5;
    ctx.set_stroke_width(1.5);
    ctx.stroke_circle(BLCircle(cx, cy, 4.0),
                      col(byp[i] ? dynui::kInkMuted : dynui::kAmber));
    if (!byp[i]) ctx.fill_circle(BLCircle(cx, cy, 2.0), col(dynui::kAmber));
  }
}

// Apply is disabled in Live mode (points are written in real-time, so there is
// nothing to "apply") - matches the GDI panel, which grayed it out under Live. The
// click is already gated by !m_liveMode in OnMouseDownPremium; this is the visual.
static void DrawFooter(BLContext& ctx, const Gfx& gfx, const DynLayout& L, bool applyEnabled) {
  ctx.set_stroke_width(1.0);
  ctx.stroke_line(BLLine(0, L.footer.y, L.footer.w, L.footer.y), col(dynui::kHairline));
  FillURound(ctx, L.apply, dynui::kRadiusCtrl, applyEnabled ? dynui::kAmber : dynui::kSurface2);
  if (gfx.fontsReady)
    TextCentered(ctx, gfx.fValue, L.apply, "Apply",
                 applyEnabled ? dynui::kSurface0 : dynui::kInkDisabled);
}

// --- View-tab toggles + Peak/RMS switch (Inc 5) ----------------------------

// One independent View-tab state toggle: rounded pill + a grayscale-legible LED
// (filled when on, hollow ring when off - the non-colour redundant cue) + an
// UPPERCASE label. On => surface3 + the data-layer colour; off => surface2 +
// secondary ink. `outline` adds an amber edge (A/B bypassed); `glow` adds a static
// additive halo on the LED (armed Live - the breathing animation is deferred motion).
static void DrawTogglePill(BLContext& ctx, const Gfx& gfx, const URect& r,
                           const char* label, bool on, uint32_t onColor,
                           bool outline, double glow) {
  if (r.w < 1.0) return;
  FillURound(ctx, r, dynui::kRadiusCtrl, on ? dynui::kSurface3 : dynui::kSurface2);
  if (on && outline) {
    ctx.set_stroke_width(1.0);
    ctx.stroke_round_rect(BLRoundRect(r.x + 0.5, r.y + 0.5, r.w - 1.0, r.h - 1.0,
                                      dynui::kRadiusCtrl), col(onColor));
  }
  const double ledR = 4.0, ledX = r.x + 12.0, ledY = r.y + r.h * 0.5;
  if (on) {
    if (glow > 0.0) {   // breathing intensity 0..1 (motion pass: Live pill pulses)
      const int a0 = (int)std::lround(60.0 * glow), a1 = (int)std::lround(110.0 * glow);
      ctx.set_comp_op(BL_COMP_OP_PLUS);
      ctx.fill_circle(BLCircle(ledX, ledY, ledR + 3.0), colA(onColor, a0));
      ctx.fill_circle(BLCircle(ledX, ledY, ledR + 1.5), colA(onColor, a1));
      ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
    }
    ctx.fill_circle(BLCircle(ledX, ledY, ledR), col(onColor));
  } else {
    ctx.set_stroke_width(1.5);
    ctx.stroke_circle(BLCircle(ledX, ledY, ledR), col(dynui::kInkMuted));
  }
  if (gfx.fontsReady)
    ctx.fill_utf8_text(BLPoint(ledX + ledR + 8.0, r.y + r.h * 0.5 + 4.0), gfx.fLabel,
                       label, SIZE_MAX, col(on ? onColor : dynui::kInkSecondary));
}

// Peak/RMS detection switch: a 2-segment mutually-exclusive pill. Active half =
// surface3 + a 2 px amber underline (the grayscale-distinct shape cue) + primary
// ink; inactive = surface1 + secondary ink. Mirrors the tab-bar's active treatment.
static void DrawSegmented2(BLContext& ctx, const Gfx& gfx, const URect& a, const URect& b,
                           const char* la, const char* lb, bool secondActive) {
  if (a.w < 1.0) return;
  const URect segs[2]  = { a, b };
  const char* labels[2] = { la, lb };
  for (int i = 0; i < 2; ++i) {
    const bool active = ((i == 1) == secondActive);
    const URect& s = segs[i];
    FillURound(ctx, s, dynui::kRadiusCtrl, active ? dynui::kSurface3 : dynui::kSurface1);
    if (active)
      ctx.fill_rect(BLRect(s.x + 6.0, s.y + s.h - 2.0, s.w - 12.0, 2.0), col(dynui::kAmber));
    if (gfx.fontsReady)
      TextCentered(ctx, gfx.fLabel, s, labels[i],
                   active ? dynui::kInkPrimary : dynui::kInkSecondary);
  }
}

// 3-segment selector (the meter-scale dB floor). Same treatment as DrawSegmented2:
// active = surface3 + a 2 px amber underline + primary ink; inactive = surface1 +
// secondary ink. Self-skips when empty (off the View tab).
static void DrawSegmentedN(BLContext& ctx, const Gfx& gfx, const URect* segs,
                           const char* const* labels, int n, int activeIdx) {
  if (segs[0].w < 1.0) return;
  for (int i = 0; i < n; ++i) {
    const bool active = (i == activeIdx);
    const URect& s = segs[i];
    FillURound(ctx, s, dynui::kRadiusCtrl, active ? dynui::kSurface3 : dynui::kSurface1);
    if (active)
      ctx.fill_rect(BLRect(s.x + 6.0, s.y + s.h - 2.0, s.w - 12.0, 2.0), col(dynui::kAmber));
    if (gfx.fontsReady)
      TextCentered(ctx, gfx.fLabel, s, labels[i],
                   active ? dynui::kInkPrimary : dynui::kInkSecondary);
  }
}

static void DrawSegmented3(BLContext& ctx, const Gfx& gfx, const URect segs[3],
                           const char* const labels[3], int activeIdx) {
  DrawSegmentedN(ctx, gfx, segs, labels, 3, activeIdx);
}

// Bottom-right corner resize grip: 3 short diagonal hairlines, kept inside the
// panel's rounded corner (radius kRadiusPanel). Drawn in base coords -> scales
// uniformly with the panel via the context transform.
static void DrawResizeGrip(BLContext& ctx, const URect& g) {
  const double cx = g.x + g.w, cy = g.y + g.h;   // panel bottom-right corner
  ctx.set_stroke_width(1.0);
  for (int i = 1; i <= 3; ++i) {
    const double d = 5.0 + (double)i * 4.0;       // 9 / 13 / 17 px bands from the corner
    ctx.stroke_line(BLLine(cx - d, cy - 5.0, cx - 5.0, cy - d), colA(dynui::kInkMuted, 170));
  }
}

// A draggable curve handle: dark-filled disc with a ring. NEUTRAL grey at rest so
// it doesn't compete with the amber operating-point dot (a readout); lights to its
// accent colour (amber/violet) only when hovered or dragged - the spec's "accent =
// active/focused" restraint. Adds an additive halo while dragged. Off-tab -> skipped.
static void DrawCurveHandle(BLContext& ctx, const URect& box, uint32_t accentCol,
                            bool lit, bool dragging) {
  if (box.w < 1.0) return;
  const double cx = box.x + box.w * 0.5, cy = box.y + box.h * 0.5;
  // At REST the handle is small + HOLLOW (no opaque centre) so the transfer curve - and
  // especially the knee rounding it sits on - reads straight through it; turning the
  // Knee knob then shows the bend instead of being masked. On hover/drag it grows,
  // lights to its accent, fills with a faint core (so it reads as grabbable), and (drag)
  // gets the additive glow. The hit-box (ComputeCurveHandles) is unchanged - still easy
  // to grab despite the smaller glyph.
  const bool active = lit || dragging;
  const double r = active ? 5.5 : 4.0;
  const uint32_t ringCol = active ? accentCol : dynui::kInkSecondary;
  if (dragging) {
    ctx.set_comp_op(BL_COMP_OP_PLUS);
    ctx.fill_circle(BLCircle(cx, cy, r + 5.0), colA(accentCol, 40));
    ctx.fill_circle(BLCircle(cx, cy, r + 2.0), colA(accentCol, 75));
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
  }
  if (active) ctx.fill_circle(BLCircle(cx, cy, r), colA(dynui::kSurface0, 150));
  ctx.set_stroke_width(active ? 2.0 : 1.5);
  ctx.stroke_circle(BLCircle(cx, cy, r), colA(ringCol, active ? 255 : 150));
}

// --- the premium panel -----------------------------------------------------

void UiCanvas::RenderPanel(HDC hdc, int x, int y, int w, int h, double dpr,
                           const DynPanelVM& vm)
{
  if (!hdc || w < 8 || h < 8) return;
  if (dpr < 1.0) dpr = 1.0;
  // Compact mode lays out in a shorter base height (plot hidden).
  const double baseH = vm.compact ? (double)dynui::kPanelHCompact : (double)dynui::kPanelH;
  // Crisp-blit invariant (v2.2.0): derive the device buffer from the EXACT integer
  // w/h that presentSurface blits, so devW == w*dpr / devH == h*dpr whenever dpr is
  // integral -> the scaled blit hits the platform's integer fast path (mac Metal 2:1)
  // instead of the soft resampler at fractional panel scales. The context then
  // scales base content to fill the buffer EXACTLY (per-axis; the sub-pixel
  // anisotropy from independent w/h rounding is invisible, while a one-axis-derived
  // buffer would leave an unpainted strip or soften the blit).
  const int devW = (int)std::lround((double)w * dpr);
  const int devH = (int)std::lround((double)h * dpr);
  if (!prepareSurface(hdc, devW, devH)) return;
  {
    BLContext ctx;
    if (ctx.begin(m_gfx->img) != BL_SUCCESS) return;
    ctx.clear_all();
    ctx.scale((double)devW / (double)dynui::kPanelW, (double)devH / baseH);
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);

    const double W = dynui::kPanelW, H = baseH;   // base layout coords (H shrinks in Compact)

    // panel slab: vertical gradient + rounded body + top hairline highlight
    {
      BLGradient bg(BLLinearGradientValues(0, 0, 0, H));
      bg.add_stop(0.0, col(dynui::kSurface1));
      bg.add_stop(1.0, col(dynui::kSurface0));
      ctx.fill_round_rect(BLRoundRect(0, 0, W, H, dynui::kRadiusPanel), bg);
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(0.5, 0.5, W - 1, H - 1, dynui::kRadiusPanel),
                            col(dynui::kHairline));
    }

    // Full chrome from the shared layout (header / tab pill / footer) + transfer
    // plot + bar-only GR meter (number is in the header) + the per-tab knob grid.
    // Hit-testing shares the same ComputeDynLayout(activeTab) so clicks always
    // match what is drawn.
    const DynLayout L = ComputeDynLayout(W, H, vm.activeTab, vm.compact);
    DrawHeader(ctx, *m_gfx, L, vm);
    DrawTabBar(ctx, *m_gfx, L, vm.activeTab, vm.tabFrom, vm.tabSlideT,
               vm.compBypass, vm.gateBypass);
    DrawFooter(ctx, *m_gfx, L, /*applyEnabled=*/!vm.liveMode);
    // Hero plot + GR meter: hidden in Compact mode (plotWell is empty there).
    if (L.plotWell.w >= 1.0) {
      DrawTransferPlot(ctx, *m_gfx, L.plotWell.x, L.plotWell.y, L.plotWell.w, vm.curve, vm.activeTab);
      DrawGrMeter(ctx, *m_gfx, L.plotWell.x + L.plotWell.w, L.plotWell.y, L.plotWell.w,
                  vm.curve, /*withNumber=*/false);
    }
    for (int i = 0; i < kDynNumParams; ++i) {
      if (i == kDynParamMaxBoost && vm.mode == 0) continue;  // M.Boost only in Up/Both
      DrawKnob(ctx, *m_gfx, L.knob[i], vm.knobs[i]);
    }

    // Peak/RMS switch (Compressor tab) + View-tab state toggles. Each helper
    // self-skips when its rect is empty, so these are no-ops on the other tabs.
    DrawSegmented2(ctx, *m_gfx, L.rms[0], L.rms[1], "PEAK", "RMS", vm.rmsMode);
    DrawTogglePill(ctx, *m_gfx, L.viewToggle[0], "DYN",  vm.showDyn,  dynui::kAmber,   false, 0.0);
    DrawTogglePill(ctx, *m_gfx, L.viewToggle[1], "ENV",  vm.showEnv,  dynui::kEnvCyan, false, 0.0);
    DrawTogglePill(ctx, *m_gfx, L.viewToggle[2], "GR",   vm.showGR,   dynui::kGrRed,   false, 0.0);
    DrawTogglePill(ctx, *m_gfx, L.viewToggle[3], "LIVE", vm.liveMode, dynui::kAmber,   false, vm.livePulse);
    // A/B is NOT a View-tab pill - it lives in the header (DrawHeader).

    // Meter-scale dB-floor selector (View tab) + its left "SCALE" caption. Both
    // self-skip when the rects are empty (off the View tab).
    static const char* const kScaleLabels[dynui::kMeterFloorOptCount] =
      { "-96", "-60", "-36", "-24" };
    DrawSegmentedN(ctx, *m_gfx, L.meterScale, kScaleLabels,
                   dynui::kMeterFloorOptCount, vm.meterFloorSel);
    if (m_gfx->fontsReady && L.meterScale[0].w >= 1.0) {
      const URect& s0 = L.meterScale[0];
      const double cw = TextWidth(m_gfx->fLabel, "SCALE");
      ctx.fill_utf8_text(BLPoint(s0.x - 8.0 - cw, s0.y + s0.h * 0.5 + 4.0), m_gfx->fLabel,
                         "SCALE", SIZE_MAX, col(dynui::kInkSecondary));
    }
    // Compact-mode toggle (View tab; self-skips when empty).
    DrawTogglePill(ctx, *m_gfx, L.compactToggle, "COMPACT", vm.compact, dynui::kAmber, false, 0.0);

    DrawResizeGrip(ctx, L.resizeGrip);

    // Curve drag-handles (on top of the plot): knee (amber, Comp) / gate (violet, Gate).
    URect handles[2];
    ComputeCurveHandles(L.plotWell, vm.curve, vm.activeTab, handles);
    DrawCurveHandle(ctx, handles[0], dynui::kAmber,
                    vm.hoverHandle == 0 || vm.dragHandle == 0, vm.dragHandle == 0);
    DrawCurveHandle(ctx, handles[1], dynui::kGateViolet,
                    vm.hoverHandle == 1 || vm.dragHandle == 1, vm.dragHandle == 1);

    if (ctx.end() != BL_SUCCESS) return;
  }
  presentSurface(hdc, x, y, w, h, devW, devH);
}

// --- the premium Settings panel (v2.2.0) ------------------------------------

// Base-coords geometry, shared with SettingsPanel hit-testing. Vertical rhythm:
// header 44, then per-section caption row + control rows with even spacing.
// kSettingsH (200) == the final y + 16 bottom pad - keep them in sync.
SettingsLayout ComputeSettingsLayout(double w, double h)
{
  (void)h;   // fixed vertical rhythm; h is the (matching) kSettingsH
  SettingsLayout L;
  const double pad = (double)dynui::kPanelPad;
  L.header   = { 0, 0, w, (double)dynui::kHeaderH };
  L.closeBtn = { w - pad - 18.0, L.header.h * 0.5 - 9.0, 18.0, 18.0 };

  double y = L.header.h + 14.0;
  L.scaleLabel = { pad, y, 120.0, 16.0 };
  L.scaleValue = { w - pad - 80.0, y, 80.0, 16.0 };
  y += 22.0;
  L.sliderRow   = { pad, y, w - 2.0 * pad, 28.0 };
  // Track inset by the thumb radius so the thumb never clips the panel edge.
  L.sliderTrack = { pad + 8.0, y + 12.0, w - 2.0 * pad - 16.0, 4.0 };
  y += 38.0;
  const double segW = (w - 2.0 * pad - 12.0) / 3.0;
  for (int i = 0; i < 3; ++i)
    L.density[i] = { pad + i * (segW + 6.0), y, segW, 28.0 };
  y += 38.0;
  L.fitBtn = { pad, y, w - 2.0 * pad, 28.0 };
  y += 28.0;

  // Migrated preference sections (A2b): divider (drawn at caption.y - 12), caption,
  // then the control row(s). Even rhythm: 12 above the divider, 12 to the caption,
  // 20 from caption top to its control row.
  y += 24.0;   // 12 gap + (divider) + 12
  L.rulerCaption = { pad, y, 160.0, 14.0 };
  y += 20.0;
  for (int i = 0; i < 3; ++i)
    L.rulerSeg[i] = { pad + i * (segW + 6.0), y, segW, 26.0 };
  y += 26.0;

  y += 24.0;
  L.metersCaption = { pad, y, 160.0, 14.0 };
  L.masterToggle  = { w - pad - 92.0, y - 4.0, 92.0, 22.0 };  // on the caption row, right
  y += 20.0;
  for (int i = 0; i < 3; ++i)
    L.meterSeg[i] = { pad + i * (segW + 6.0), y, segW, 26.0 };
  y += 26.0;

  y += 24.0;
  L.viewCaption = { pad, y, 160.0, 14.0 };
  y += 20.0;
  const double pillW = (w - 2.0 * pad - 8.0) / 2.0;
  L.viewToggle[0] = { pad, y, pillW, 26.0 };                  // METERS
  L.viewToggle[1] = { pad + pillW + 8.0, y, pillW, 26.0 };    // RMS
  y += 32.0;
  L.viewToggle[2] = { pad, y, pillW, 26.0 };                  // SNAP TO ZERO
  L.viewToggle[3] = { pad + pillW + 8.0, y, pillW, 26.0 };    // MINIMAP
  y += 32.0;
  L.zoomSeg[0] = { pad, y, pillW, 26.0 };                     // ZOOM: MOUSE
  L.zoomSeg[1] = { pad + pillW + 8.0, y, pillW, 26.0 };       // ZOOM: CURSOR
  // final y + 26 + 16 bottom pad == kSettingsH (474) - keep in sync with ui_theme.h
  return L;
}

void UiCanvas::RenderSettingsPanel(HDC hdc, int x, int y, int w, int h, double dpr,
                                   const SettingsVM& vm)
{
  if (!hdc || w < 8 || h < 8) return;
  if (dpr < 1.0) dpr = 1.0;
  // Crisp-blit invariant: device buffer from the exact blitted w/h; the context
  // scales base content to fill it exactly (see RenderPanel for the rationale).
  const int devW = (int)std::lround((double)w * dpr);
  const int devH = (int)std::lround((double)h * dpr);
  if (!prepareSurface(hdc, devW, devH)) return;
  {
    BLContext ctx;
    if (ctx.begin(m_gfx->img) != BL_SUCCESS) return;
    ctx.clear_all();
    ctx.scale((double)devW / (double)dynui::kSettingsW,
              (double)devH / (double)dynui::kSettingsH);
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
    const Gfx& gfx = *m_gfx;
    const double W = (double)dynui::kSettingsW, H = (double)dynui::kSettingsH;

    // panel slab: same treatment as the dynamics panel (gradient + hairline)
    {
      BLGradient bg(BLLinearGradientValues(0, 0, 0, H));
      bg.add_stop(0.0, col(dynui::kSurface1));
      bg.add_stop(1.0, col(dynui::kSurface0));
      ctx.fill_round_rect(BLRoundRect(0, 0, W, H, dynui::kRadiusPanel), bg);
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(0.5, 0.5, W - 1, H - 1, dynui::kRadiusPanel),
                            col(dynui::kHairline));
    }

    const SettingsLayout L = ComputeSettingsLayout(W, H);

    // header: title + close
    if (gfx.fontsReady) {
      ctx.fill_utf8_text(BLPoint(dynui::kPanelPad, L.header.h * 0.5 + 5.0), gfx.fValue,
                         "SETTINGS", SIZE_MAX, col(dynui::kInkPrimary));
      TextCentered(ctx, gfx.fValue, L.closeBtn, "x",
                   vm.hover == SET_HIT_CLOSE ? dynui::kInkPrimary : dynui::kInkMuted);
    }
    ctx.set_stroke_width(1.0);
    ctx.stroke_line(BLLine(0, L.header.h, W, L.header.h), col(dynui::kHairline));

    // UI SCALE caption + live % readout (amber while dragging)
    if (gfx.fontsReady) {
      ctx.fill_utf8_text(BLPoint(L.scaleLabel.x, L.scaleLabel.y + 12.0), gfx.fLabel,
                         "UI SCALE", SIZE_MAX, col(dynui::kInkSecondary));
      char pct[16];
      std::snprintf(pct, sizeof(pct), "%d%%", (int)std::lround(vm.uiScale * 100.0));
      const double tw = TextWidth(gfx.fValue, pct);
      ctx.fill_utf8_text(BLPoint(L.scaleValue.x + L.scaleValue.w - tw, L.scaleValue.y + 13.0),
                         gfx.fValue, pct, SIZE_MAX,
                         col(vm.dragging ? dynui::kAmber : dynui::kInkPrimary));
    }

    // slider: rail + amber fill + 100% reference notch + thumb (glow on hover/drag)
    {
      const double norm = std::clamp((vm.uiScale - 0.8) / 1.2, 0.0, 1.0);
      const double cy = L.sliderTrack.y + L.sliderTrack.h * 0.5;
      const double tx = L.sliderTrack.x + norm * L.sliderTrack.w;
      FillURound(ctx, L.sliderTrack, 2.0, dynui::kSurface2);
      if (tx > L.sliderTrack.x + 0.5)
        ctx.fill_round_rect(BLRoundRect(L.sliderTrack.x, L.sliderTrack.y,
                                        tx - L.sliderTrack.x, L.sliderTrack.h, 2.0),
                            col(dynui::kAmber));
      {
        const double nx = L.sliderTrack.x + ((1.0 - 0.8) / 1.2) * L.sliderTrack.w;
        ctx.fill_rect(BLRect(nx - 0.75, cy - 8.0, 1.5, 4.5), colA(dynui::kInkMuted, 180));
      }
      const bool hot = vm.dragging || vm.hover == SET_HIT_SLIDER;
      if (hot) {
        ctx.set_comp_op(BL_COMP_OP_PLUS);
        ctx.fill_circle(BLCircle(tx, cy, 11.0), colA(dynui::kAmber, 26));
        ctx.fill_circle(BLCircle(tx, cy, 8.5), colA(dynui::kAmber, 40));
        ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
      }
      ctx.fill_circle(BLCircle(tx, cy, 7.0), col(dynui::kAmber));
      ctx.fill_circle(BLCircle(tx, cy, 2.6), col(dynui::kSurface0));
    }

    // density presets: 3-segment selector; the segment matching the current scale
    // lights up (none when the slider sits between presets)
    {
      static const char* const kDensityLabels[3] = { "COMPACT", "COMFORTABLE", "SPACIOUS" };
      int active = -1;
      for (int i = 0; i < 3; ++i)
        if (std::fabs(vm.uiScale - dynui::kDensityScale[i]) < 0.005) active = i;
      DrawSegmented3(ctx, gfx, L.density, kDensityLabels, active);
    }

    // fit-to-window
    FillURound(ctx, L.fitBtn, dynui::kRadiusCtrl,
               vm.hover == SET_HIT_FIT ? dynui::kSurface3 : dynui::kSurface2);
    if (gfx.fontsReady)
      TextCentered(ctx, gfx.fLabel, L.fitBtn, "FIT TO WINDOW",
                   vm.hover == SET_HIT_FIT ? dynui::kInkPrimary : dynui::kInkSecondary);

    // Migrated preference sections (A2b): divider + caption + controls each.
    auto sectionCaption = [&](const URect& cap, const char* text) {
      ctx.set_stroke_width(1.0);
      ctx.stroke_line(BLLine(dynui::kPanelPad, cap.y - 12.0,
                             W - dynui::kPanelPad, cap.y - 12.0), col(dynui::kHairline));
      if (gfx.fontsReady)
        ctx.fill_utf8_text(BLPoint(cap.x, cap.y + 11.0), gfx.fLabel, text, SIZE_MAX,
                           col(dynui::kInkSecondary));
    };

    // RULER: time display mode
    sectionCaption(L.rulerCaption, "RULER");
    {
      static const char* const kRulerLabels[3] = { "RELATIVE", "ABSOLUTE", "BARS/BEATS" };
      DrawSegmented3(ctx, gfx, L.rulerSeg, kRulerLabels, vm.prefs.rulerMode);
    }

    // METERS: detection mode + master-output source pill on the caption row
    sectionCaption(L.metersCaption, "METERS");
    DrawTogglePill(ctx, gfx, L.masterToggle, "MASTER", vm.prefs.meterFromMaster,
                   dynui::kAmber, false, 0.0);
    {
      static const char* const kMeterLabels[3] = { "PEAK", "RMS", "VU" };
      DrawSegmented3(ctx, gfx, L.meterSeg, kMeterLabels, vm.prefs.meterMode);
    }

    // VIEW: independent display toggles
    sectionCaption(L.viewCaption, "VIEW");
    DrawTogglePill(ctx, gfx, L.viewToggle[0], "METERS",       vm.prefs.showMeters, dynui::kAmber, false, 0.0);
    DrawTogglePill(ctx, gfx, L.viewToggle[1], "RMS",          vm.prefs.showRMS,    dynui::kAmber, false, 0.0);
    DrawTogglePill(ctx, gfx, L.viewToggle[2], "SNAP TO ZERO", vm.prefs.snapZero,   dynui::kAmber, false, 0.0);
    DrawTogglePill(ctx, gfx, L.viewToggle[3], "MINIMAP",      vm.prefs.minimap,    dynui::kAmber, false, 0.0);
    // Wheel-zoom center (#83): a 2-way selector, mouse position vs edit cursor.
    // "EDIT CURSOR" spelled out (REAPER's own term) - bare "CURSOR" reads as the
    // mouse pointer, the exact ambiguity this option exists to resolve.
    DrawSegmented2(ctx, gfx, L.zoomSeg[0], L.zoomSeg[1], "ZOOM: MOUSE", "ZOOM: EDIT CURSOR",
                   vm.prefs.zoomOnCursor);

    if (ctx.end() != BL_SUCCESS) return;
  }
  presentSurface(hdc, x, y, w, h, devW, devH);
}

// --- the premium gain knob overlay (v2.2.0 Inc D) ----------------------------

void UiCanvas::RenderGainPanel(HDC hdc, int x, int y, int w, int h, double dpr,
                               const GainVM& vm)
{
  if (!hdc || w < 8 || h < 8) return;
  if (dpr < 1.0) dpr = 1.0;
  // Base layout = the GDI panel's 110x32 literal coords (knob zone x<32, readout
  // 32..96, close 96..110/y<14), so GainPanel's SP()-scaled hit-test matches.
  // Crisp-blit invariant: device buffer from the exact blitted w/h (see RenderPanel).
  const double BW = 110.0, BH = 32.0;
  const int devW = (int)std::lround((double)w * dpr);
  const int devH = (int)std::lround((double)h * dpr);
  if (!prepareSurface(hdc, devW, devH)) return;
  {
    BLContext ctx;
    if (ctx.begin(m_gfx->img) != BL_SUCCESS) return;
    ctx.clear_all();
    ctx.scale((double)devW / BW, (double)devH / BH);
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
    const Gfx& gfx = *m_gfx;

    // slab (small: control radius, not panel radius)
    {
      BLGradient bg(BLLinearGradientValues(0, 0, 0, BH));
      bg.add_stop(0.0, col(dynui::kSurface1));
      bg.add_stop(1.0, col(dynui::kSurface0));
      ctx.fill_round_rect(BLRoundRect(0, 0, BW, BH, dynui::kRadiusCtrl), bg);
      ctx.set_stroke_width(1.0);
      ctx.stroke_round_rect(BLRoundRect(0.5, 0.5, BW - 1, BH - 1, dynui::kRadiusCtrl),
                            col(dynui::kHairline));
    }

    // knob: same 270deg geometry as the dynamics knobs (screen 135deg + sweep 270)
    const double cx = 18.0, cy = BH * 0.5, r = 10.0;
    const double a0 = Deg2Rad(135.0), sweep = Deg2Rad(270.0);
    const uint32_t accent = vm.boost ? dynui::kGrRed : dynui::kAmber;
    ctx.set_stroke_width(2.5);
    { BLPath p; p.arc_to(cx, cy, r, r, a0, sweep, true); ctx.stroke_path(p, col(dynui::kSurface3)); }
    // active arc: 0 dB notch -> current value
    {
      const double nLo = std::min(vm.zeroNorm, vm.valNorm);
      const double nHi = std::max(vm.zeroNorm, vm.valNorm);
      if (nHi - nLo > 0.002) {
        BLPath p;
        p.arc_to(cx, cy, r, r, a0 + sweep * nLo, sweep * (nHi - nLo), true);
        ctx.stroke_path(p, col(accent));
      }
    }
    // cap + pointer
    ctx.fill_circle(BLCircle(cx, cy, r - 3.5), col(dynui::kSurface2));
    {
      const double a = a0 + sweep * std::clamp(vm.valNorm, 0.0, 1.0);
      ctx.set_stroke_width(2.0);
      ctx.stroke_line(BLLine(cx + std::cos(a) * 2.5, cy + std::sin(a) * 2.5,
                             cx + std::cos(a) * (r - 1.5), cy + std::sin(a) * (r - 1.5)),
                      col(accent));
    }
    // 0 dB notch tick just outside the ring
    {
      const double a = a0 + sweep * std::clamp(vm.zeroNorm, 0.0, 1.0);
      ctx.set_stroke_width(1.0);
      ctx.stroke_line(BLLine(cx + std::cos(a) * (r + 1.0), cy + std::sin(a) * (r + 1.0),
                             cx + std::cos(a) * (r + 4.0), cy + std::sin(a) * (r + 4.0)),
                      colA(dynui::kInkMuted, 200));
    }

    // dB readout, centered in [32, 96] (gold tint = batch relative mode)
    if (gfx.fontsReady && vm.text) {
      const URect tr{ 32.0, 0.0, 64.0, BH };
      const uint32_t ink = vm.boost ? dynui::kGrRed
                         : vm.gold  ? dynui::kAmberGlow : dynui::kInkPrimary;
      TextCentered(ctx, gfx.fTab, tr, vm.text, ink);
    }
    // close x (top-right 14px zone)
    if (gfx.fontsReady) {
      const URect xr{ BW - 14.0, 0.0, 14.0, 16.0 };
      TextCentered(ctx, gfx.fLabel, xr, "x", dynui::kInkMuted);
    }

    if (ctx.end() != BL_SUCCESS) return;
  }
  presentSurface(hdc, x, y, w, h, devW, devH);
}

// --- the premium L/R meters (v2.2.0 Inc E) -----------------------------------

void UiCanvas::RenderMeters(HDC hdc, int x, int y, int w, int h, double dpr,
                            const MetersVM& vm)
{
  if (!hdc || w < 16 || h < 16) return;
  if (dpr < 1.0) dpr = 1.0;
  // The meters fill a layout rect (variable size), so the base coords are the
  // rect divided by the global UI scale - content (bars, fonts, spacing) then
  // scales with the UI like the fixed-base panels do.
  const double S = vm.uiScale > 0.0 ? vm.uiScale : 1.0;
  const double BW = (double)w / S, BH = (double)h / S;
  const int devW = (int)std::lround((double)w * dpr);
  const int devH = (int)std::lround((double)h * dpr);
  if (!prepareSurface(hdc, devW, devH)) return;
  {
    BLContext ctx;
    if (ctx.begin(m_gfx->img) != BL_SUCCESS) return;
    ctx.clear_all();
    ctx.scale((double)devW / BW, (double)devH / BH);
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
    const Gfx& gfx = *m_gfx;

    // background slab (flat surface0 - sits inside the GDI bottom panel)
    ctx.fill_rect(BLRect(0, 0, BW, BH), col(dynui::kSurface0));

    // geometry: mirrors the GDI meter (labels left, bars right, scale row below)
    const double scaleH = 12.0, gap = 2.0, labelW = 14.0;
    const double barsH = BH - scaleH;
    const int numCh = vm.numCh >= 2 ? 2 : 1;
    const double barH = (numCh == 2) ? (barsH - gap) / 2.0 : barsH;
    const double barLeft = labelW, barRight = BW - 2.0;
    const double barW = barRight - barLeft;
    if (barW < 10.0) { ctx.end(); return; }

    // per-mode bar shades (Peak bright / RMS mid / VU dim - the GDI distinction)
    struct Shades { uint32_t g, yel, r; };
    static const Shades kShades[3] = {
      { 0xFF32D25A, 0xFFD2BE28, 0xFFDC3232 },   // PEAK
      { 0xFF28A03C, 0xFFBEAA1E, 0xFFC82828 },   // RMS
      { 0xFF1E9646, 0xFFB4A01E, 0xFFBE2828 },   // VU
    };
    const Shades& sh = kShades[vm.mode >= 0 && vm.mode <= 2 ? vm.mode : 0];
    const double nYellow = (-18.0 + 60.0) / 60.0;   // zone boundaries (dB -> norm)
    const double nRed    = (-6.0 + 60.0) / 60.0;

    static const char* const chLabels2[2] = { "L", "R" };
    for (int ch = 0; ch < numCh; ++ch) {
      const double yTop = ch * (barH + gap);

      // channel label
      if (gfx.fontsReady)
        TextCentered(ctx, gfx.fTick, URect{ 0.0, yTop, labelW, barH },
                     numCh == 1 ? "M" : chLabels2[ch], dynui::kInkSecondary);

      // bar well
      ctx.fill_round_rect(BLRoundRect(barLeft, yTop, barW, barH, 2.0),
                          col(dynui::kSurface2));

      // value bar: green->yellow->red gradient, clipped to the current level
      const double bn = std::clamp(vm.barNorm[ch], 0.0, 1.0);
      if (bn > 0.003) {
        BLGradient g(BLLinearGradientValues(barLeft, 0, barLeft + barW, 0));
        g.add_stop(0.0,            col(sh.g));
        g.add_stop(nYellow - 0.02, col(sh.g));
        g.add_stop(nYellow + 0.02, col(sh.yel));
        g.add_stop(nRed - 0.02,    col(sh.yel));
        g.add_stop(nRed + 0.02,    col(sh.r));
        g.add_stop(1.0,            col(sh.r));
        ctx.save();
        ctx.clip_to_rect(BLRect(barLeft, yTop, barW * bn, barH));
        ctx.fill_round_rect(BLRoundRect(barLeft, yTop + 1.0, barW, barH - 2.0, 2.0), g);
        ctx.restore();
      }

      // dB ticks inside the well (subtle)
      static const double kTicksDb[] = { -48, -36, -24, -18, -12, -6, -3 };
      for (double db : kTicksDb) {
        const double tx = barLeft + ((db + 60.0) / 60.0) * barW;
        ctx.fill_rect(BLRect(tx, yTop + 1.0, 1.0, barH - 2.0), colA(0xFFFFFFFF, 14));
      }

      // peak-hold: 2px line colored by zone
      const double pn = std::clamp(vm.peakNorm[ch], 0.0, 1.0);
      if (pn > 0.01) {
        const uint32_t pc = pn > nRed ? sh.r : pn > nYellow ? sh.yel : sh.g;
        ctx.fill_rect(BLRect(barLeft + pn * barW - 1.0, yTop, 2.0, barH), col(pc));
      }
    }

    // scale row: mode caption + dB numbers under the bars
    if (gfx.fontsReady) {
      const double sy = BH - scaleH;
      TextCentered(ctx, gfx.fTick, URect{ 0.0, sy, labelW, scaleH },
                   vm.modeLabel ? vm.modeLabel : "dB", dynui::kInkMuted);
      static const double kMarksDb[] = { -54, -48, -42, -36, -30, -24, -18, -12, -6, -3, 0 };
      for (double db : kMarksDb) {
        const double mx = barLeft + ((db + 60.0) / 60.0) * barW;
        ctx.fill_rect(BLRect(mx, sy, 1.0, 3.0), colA(0xFFFFFFFF, 30));
        char buf[8];
        std::snprintf(buf, sizeof(buf), "%.0f", db);
        TextCentered(ctx, gfx.fTick, URect{ mx - 14.0, sy + 2.0, 28.0, scaleH - 2.0 },
                     buf, dynui::kInkMuted);
      }
    }

    if (ctx.end() != BL_SUCCESS) return;
  }
  presentSurface(hdc, x, y, w, h, devW, devH);
}

// --- the premium toast (v2.2.0 Inc F) ----------------------------------------

void UiCanvas::RenderToast(HDC hdc, int x, int y, int w, int h, double dpr,
                           const ToastVM& vm)
{
  if (!hdc || w < 8 || h < 8 || !vm.text || !vm.text[0]) return;
  if (dpr < 1.0) dpr = 1.0;
  const double S = vm.uiScale > 0.0 ? vm.uiScale : 1.0;
  const double BW = (double)w / S, BH = (double)h / S;
  const int devW = (int)std::lround((double)w * dpr);
  const int devH = (int)std::lround((double)h * dpr);
  if (!prepareSurface(hdc, devW, devH)) return;
  {
    BLContext ctx;
    if (ctx.begin(m_gfx->img) != BL_SUCCESS) return;
    ctx.clear_all();
    ctx.scale((double)devW / BW, (double)devH / BH);
    ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
    const Gfx& gfx = *m_gfx;

    // Opaque underlay in the waveform bg color (the blit rect is opaque; this
    // makes it blend with what it covers), then the pill composites over it
    // with the fade alpha - a real alpha fade against the right background.
    ctx.fill_rect(BLRect(0, 0, BW, BH), col(vm.bgColor));
    ctx.set_global_alpha(std::clamp(vm.alpha, 0.0, 1.0));

    BLGradient bg(BLLinearGradientValues(0, 0, 0, BH));
    bg.add_stop(0.0, col(dynui::kSurface3));
    bg.add_stop(1.0, col(dynui::kSurface1));
    ctx.fill_round_rect(BLRoundRect(0, 0, BW, BH, dynui::kRadiusCtrl), bg);
    ctx.set_stroke_width(1.0);
    ctx.stroke_round_rect(BLRoundRect(0.5, 0.5, BW - 1, BH - 1, dynui::kRadiusCtrl),
                          col(dynui::kHairline));
    if (gfx.fontsReady)
      TextCentered(ctx, gfx.fTab, URect{ 0.0, 0.0, BW, BH }, vm.text,
                   dynui::kInkPrimary);

    if (ctx.end() != BL_SUCCESS) return;
  }
  presentSurface(hdc, x, y, w, h, devW, devH);
}
